!=====================================================================================================================================
      Subroutine MAXSTRESSCALCULATION(NNODE,NOUTCORD,NNCORD,NPLANE,NELECAL,MN,
     1      BRACEDIAMETER,CHORDDIMETER,BRACETHICKNESS,CHORDTHICKNESS,M,INDEX,NJOINT,ITIME,NFATIGUELOOPOUT)  
      
      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT INTEGER*4 (i-n)
      CHARACTER*3 NJOINT
      CHARACTER*4 CONDITION
      CHARACTER*2 HOPPOSITION
      
      DIMENSION NOUTCORD(NNCORD),NELECAL(MN)
      DIMENSION BRACEDIAMETER(M),CHORDDIMETER(M)
      DIMENSION BRACETHICKNESS(M),CHORDTHICKNESS(M)
      DIMENSION AHOTSPOT_CHORD(8)
      DIMENSION AHOTSPOT_BRACE(8)

      COMMON / HEADLINE / Nheaderinnitialjointfatigue,JCHANA
      COMMON/FATIGUE_TIMEDYNA/ TIMEDYNA
      
      COMMON /TIME/ DDT,CTIM,NINC
      COMMON /LINEAT/ KTRAF,KEATH,KCSAL,KOFFL,KSPEC,KDESIGN,KFATM,KFATJ,KFATL,KFAST,KOREV,KFTTD
      
      COMMON / LOCALFORCE / DESIGNAXIAL(500000),DESIGNSHEART(500000),DESIGNSHEARS(500000)
     1                     ,DESIGNTORSION(500000),DESIGNMOMENTT(500000),DESIGNMOMENTS(500000)
      
      COMMON /AHOTSPORT/AHOTSPORTCHORDSADDLE(5,2),AHOTSPORTCHORDCROWN(5,2),AHOTSPORTBRACESADDLE(5,2),AHOTSPORTBRACECROWN(5,2)
     1 ,AHOTSPORTCHORDSADDLE_AXIAL(5,2),AHOTSPORTCHORDCROWN_AXIAL(5,2),AHOTSPORTBRACESADDLE_AXIAL(5,2)
     1 ,AHOTSPORTBRACECROWN_AXIAL(5,2)
     1  ,AHOTSPORTCHORDSADDLE_TT(5,2),AHOTSPORTCHORDCROWN_TT(5,2),AHOTSPORTBRACESADDLE_TT(5,2),AHOTSPORTBRACECROWN_TT(5,2)
     1  ,AHOTSPORTCHORDSADDLE_SS(5,2),AHOTSPORTCHORDCROWN_SS(5,2),AHOTSPORTBRACESADDLE_SS(5,2),AHOTSPORTBRACECROWN_SS(5,2)
     1  ,AHOTSPORTCHORDSADDLE_MX(5,2),AHOTSPORTCHORDCROWN_MX(5,2),AHOTSPORTBRACESADDLE_MX(5,2),AHOTSPORTBRACECROWN_MX(5,2)
      
            
      COMMON /SCFFACTOR/SCFCHORDSADDLEJOINT(5,2),SCFCHORDCROWNJOINT(5,2),SCFBRACESADDLEJOINT(5,2),
     1        SCFBRACECROWNJOINT(5,2),
     1 SCFCHORDSADDLEJOINT_AXIAL(5,2),SCFCHORDCROWNJOINT_AXIAL(5,2),SCFBRACESADDLEJOINT_AXIAL(5,2),SCFBRACECROWNJOINT_AXIAL(5,2),
     1        SCFCHORDSADDLEJOINT_TT(5,2),SCFCHORDCROWNJOINT_TT(5,2),SCFBRACESADDLEJOINT_TT(5,2),SCFBRACECROWNJOINT_TT(5,2),
     1        SCFCHORDSADDLEJOINT_SS(5,2),SCFCHORDCROWNJOINT_SS(5,2),SCFBRACESADDLEJOINT_SS(5,2),SCFBRACECROWNJOINT_SS(5,2)
      
      COMMON /JOINTMANUAL/ NNODEJOINTM(1000),NNPLANE(1000),SCFCHORDCROWN(1000),SCFCHORDSADDLE(1000),SCFACROWN(1000),SCFBCROWN(1000)
     1                    ,SCFCCROWN(1000),SCFASADDLE(1000),SCFBCSADDLE(1000),SCFCSADDLE(1000),JOINTLOOPMANUAL
     
      COMMON / SCFMANUAL /  SCFCHORDSADDLEMANL(2,1000,2),  SCFCHORDCROWNMANL(2,1000,2)
     1                     ,SCFBRACESADDLEMANL_A(1000,2,3),SCFBRACECROWNMANL_A(1000,2,3),SFMANUAL(1000,2),LIFEMANUAL(1000,2)  
      COMMON /INDEXSTOREX/ INDEXSTORE
      COMMON /SAFTYMANUALXX/ NUMBERCHORD(10000),NUMBERBRACE(10000),NUMBERNPLANE(10000)

            
            
      CALL OFFSHSTEP(TIME,ITIME,NTIME,'CALL') 
      
      if(KFTTD.eq.1)  TIME = CTIM
      
      IF(Nheaderinnitialjointfatigue .EQ.1) THEN
           
      CALL SCF_JOINT_CONDITION(NNODE,CONDITION)
      
      !WRITE(940,*)'JONT_NUMB   FREQ   LOOP CONNECT PLAN TYPE    MEMBER SADDL_HOTSPOT CROWN_HOTSPOT'
      WRITE(940,*)'JONT_NUMB   FREQ   LOOP CONNECT PLAN TYPE    MEMBER  LOCAL  HOTSPOT_STRESS'
      
      WRITE(960,770) ',' , ',' , ',' , ',' ,',' , ',' , ',' , ',' 
      
770   FORMAT('JONT_NUMB',A,'FREQ',A,'LOOP',A,'CONNECT',A,'PLAN',A,'TYPE ',A,'MEMBER',A,'SADDL_HOTSPOT',A,'CROWN_HOTSPOT') 
      
       ! WRITE(960,*)  123
      
      write(5005,*)'NODE    Frequency Scat  Member  Plane Joint    Member Local Hotsport_stress'
      !write(5005,5105)NNODE,TIME,NFATIGUELOOPOUT,INDEBRACE,NPLANE,NJOINT,HOPPOSITION,AMAXHOTSOPT

      write(5004,7791)
7791  format('  NODE Memb_Num  Member    Plane  Streee_P1   Streee_P2   Streee_P3   Streee_P4   Streee_P5   Streee_P6 
     1 Streee_P7   Streee_P8')
!      write(5004,5104)NNODE,INDEBRACE,'CHORD',NPLANE,StressPoint_1 , StressPoint_2, StressPoint_3, StressPoint_4,StressPoint_5
!     1 ,StressPoint_6 , StressPoint_7, StressPoint_8
             
             
      ENDIF
      
C     M  = TOTAOL NUMBER OF ELEMENT AT INTERREST POINT (JOINT)  
      
      NUMBEROFJOINT = NNODE
      !DO IPLANE = 1 , 2 !PLANE
      write(948,*)'NCORD PLANE TYPE    MEMBER SADDL_SCF   SADDL_HOTSPOT   CROWN_SCF  CROWN_HOTSPOT'
      
      write(938,798) ',' , ',' , ',' , ',' , ',' , ',' , ',' , ',' 
      
798   FORMAT( 'NCORD' ,A,' PLANE ',A,'TYPE',A, 'MEMBER' ,A,' SADDL_SCF' ,A,'SADDL_HOTSPOT',A, 'CROWN_SCF ',A, 'CROWN_HOTSPOT'
     1  ,A, 'ANALYS') !,A,A)
            
      IF (CONDITION.EQ.'AUTO')THEN   
      write(949,*)'NCORD PLANE TYPE    MEMBER SADDL_SCF   SADDL_HOTSPOT   CROWN_SCF  CROWN_HOTSPOT' 
      
      
      write(939,797) ',' , ',' , ',' , ',' , ',' , ',' , ',' , ',' 
      
797   FORMAT( 'NCORD' ,A,' PLANE ',A,'TYPE',A, 'MEMBER' ,A,' SADDL_SCF' ,A,'SADDL_HOTSPOT',A, 'CROWN_SCF ',A, 'CROWN_HOTSPOT'
     1  ,A, 'ANALYS') !,A,A)
            
            
      ENDIF
      
      !write(950,*)'NCORD PLANE  TYPE  CHORDSADDLSCF   CHORDCROWNSCF  BRACESADDLESCF  BRACECROWNSCF
      

      
      DO INDEX = 1 , NNCORD
      INDCHORD  = NOUTCORD(INDEX)
       
      
      !==============================
      ! GETTING CHORD AXIAL FORCE
      !==============================
      
      AFXX = DESIGNAXIAL(INDCHORD) ! AXIAL FORCE
      AFTT = DESIGNSHEART(INDCHORD)
      AFSS = DESIGNSHEARS(INDCHORD)
      AMTO = DESIGNTORSION(INDCHORD)
      AMTT = DESIGNMOMENTT(INDCHORD)
      AMSS = DESIGNMOMENTS(INDCHORD)
      
      write(5001,5101)NNODE,INDCHORD,'CHORD',NPLANE,AFXX,AFTT,AFSS,AMTO,AMTT,AMSS
5101  format(i6,3X,i6,3X,A5,6X,I1,1X,6E12.4,4X)     
      
      !==============================
      ! CHORD PROPERTY CALCULATION
      !==============================
      
      PI= 3.141592654D0
      DIACHORD = CHORDDIMETER(INDEX)
      THICKCHORD = CHORDTHICKNESS(INDEX)
      
      AREACHORD =  PI * (DIACHORD**2D0 - (DIACHORD-2D0*THICKCHORD)**2D0  ) / 4D0
      
      AMOMENTOFINTIA = PI * (DIACHORD**2D0 - (DIACHORD-4D0*THICKCHORD)**4D0  ) / 64D0
      
      STRESSFXX = AFXX / AREACHORD ! STRESS CALCULATION 
      STRESSFTT = AFTT / AREACHORD
      STRESSFSS = AFSS / AREACHORD
      
      STRESSMTT  = AMTT * 0.5D0 * DIACHORD   / AMOMENTOFINTIA
      STRESSMSS  = AMSS * 0.5D0 * DIACHORD   / AMOMENTOFINTIA
      STRESSMTO  = AMTO * 0.5D0 * DIACHORD   / (2*AMOMENTOFINTIA)
      
      write(5002,5101)NNODE,INDCHORD,'CHORD',NPLANE,STRESSFXX,STRESSFTT,STRESSFSS,STRESSMTO,STRESSMTT,STRESSMSS
      !TIMEDYNA
      
      ! write(5012,5112)NNODE,INDCHORD,'CHORD',NPLANE,TIMEDYNA,STRESSFXX,STRESSFTT,STRESSFSS,STRESSMTO,STRESSMTT,STRESSMSS


      
      !======================================
      
      
      CALL SCF_JOINT_CONDITION(NUMBEROFJOINT,CONDITION)
      
      SELECTCASE(CONDITION)


      CASE('MANL')
          
      !SCFCHORDCROWN(1000),SCFCHORDSADDLE(1000)
          
          XCHECK1 = SCFCHORDSADDLEMANL(NPLANE,NNODE,INDEX)
          XCHECK2 = SCFCHORDCROWNMANL(NPLANE,NNODE,INDEX)
      
           write(9970,*) STRESSFXX , STRESSFXX
      
      AHOTSPORTCHORDSADDLE_AXIAL(INDEX,NPLANE) = STRESSFXX * SCFCHORDSADDLEMANL(NPLANE,NNODE,INDEX) !!
      AHOTSPORTCHORDCROWN_AXIAL(INDEX,NPLANE)  = STRESSFXX * SCFCHORDCROWNMANL(NPLANE,NNODE,INDEX)
      
      AHOTSPORTCHORDSADDLE_TT(INDEX,NPLANE) = STRESSMTT * 0D0
      AHOTSPORTCHORDCROWN_TT(INDEX,NPLANE)  = STRESSMTT * 0D0
      
      AHOTSPORTCHORDSADDLE_SS(INDEX,NPLANE) = STRESSMSS * 0D0 
      AHOTSPORTCHORDCROWN_SS(INDEX,NPLANE)  = STRESSMSS * 0D0    
          
      !=================================
      ! STRESS SUPERPOSITION
      !=================================
      
      AHOTSPORTCHORDSADDLE_MX(INDEX,NPLANE)  = (AHOTSPORTCHORDSADDLE_AXIAL(INDEX,NPLANE)) + 
     1 ( AHOTSPORTCHORDSADDLE_TT(INDEX,NPLANE) ) + AHOTSPORTCHORDSADDLE_SS(INDEX,NPLANE)
      
      AHOTSPORTCHORDCROWN_MX(INDEX,NPLANE)   =  (AHOTSPORTCHORDCROWN_AXIAL(INDEX,NPLANE))  + 
     1   AHOTSPORTCHORDCROWN_TT(INDEX,NPLANE)  +  AHOTSPORTCHORDCROWN_SS(INDEX,NPLANE)  
      
      CASE('AUTO')    
     
      !==================================
      ! HOTSPOT CHORD STRESS CALCULATION
      !==================================

            write(9970,*) STRESSBFXX , STRESSBFXX, 'AUTO'
      
      AHOTSPORTCHORDSADDLE_AXIAL(INDEX,NPLANE) = STRESSFXX * SCFCHORDSADDLEJOINT_AXIAL(INDEX,NPLANE)
      AHOTSPORTCHORDCROWN_AXIAL(INDEX,NPLANE)  = STRESSFXX * SCFCHORDCROWNJOINT_AXIAL(INDEX,NPLANE)
      
      AHOTSPORTCHORDSADDLE_TT(INDEX,NPLANE) = STRESSMTT * SCFCHORDSADDLEJOINT_TT(INDEX,NPLANE)
      AHOTSPORTCHORDCROWN_TT(INDEX,NPLANE)  = STRESSMTT * SCFCHORDCROWNJOINT_TT(INDEX,NPLANE)
      
      AHOTSPORTCHORDSADDLE_SS(INDEX,NPLANE) = STRESSMSS * SCFCHORDSADDLEJOINT_SS(INDEX,NPLANE)
      AHOTSPORTCHORDCROWN_SS(INDEX,NPLANE)  = STRESSMSS * SCFCHORDCROWNJOINT_SS(INDEX,NPLANE)
      
    
      !=================================
      ! STRESS SUPERPOSITION
      !=================================
      
      AHOTSPORTCHORDSADDLE_MX(INDEX,NPLANE)  = (AHOTSPORTCHORDSADDLE_AXIAL(INDEX,NPLANE)) + 
     1 ( AHOTSPORTCHORDSADDLE_TT(INDEX,NPLANE) ) + AHOTSPORTCHORDSADDLE_SS(INDEX,NPLANE)
      
      AHOTSPORTCHORDCROWN_MX(INDEX,NPLANE)   =  (AHOTSPORTCHORDCROWN_AXIAL(INDEX,NPLANE))  + 
     1   AHOTSPORTCHORDCROWN_TT(INDEX,NPLANE)  +  AHOTSPORTCHORDCROWN_SS(INDEX,NPLANE) 
      

      write(949,903)INDCHORD,NPLANE,NJOINT,SCFCHORDSADDLEJOINT_AXIAL(INDEX,NPLANE),AHOTSPORTCHORDSADDLE_AXIAL(INDEX,NPLANE),
     1 SCFCHORDCROWNJOINT_AXIAL(INDEX,NPLANE),AHOTSPORTCHORDCROWN_AXIAL(INDEX,NPLANE),CONDITION
      
903   format(I5,2X,I4,3X,A3,4X,'CH_AX',1X,F10.3,4X,E12.5,2X,F10.3,3X,E12.5,4X,A4)
      
      write(949,904)INDCHORD,NPLANE,NJOINT,SCFCHORDSADDLEJOINT_TT(INDEX,NPLANE),AHOTSPORTCHORDSADDLE_TT(INDEX,NPLANE),
     1 SCFCHORDCROWNJOINT_TT(INDEX,NPLANE),AHOTSPORTCHORDCROWN_TT(INDEX,NPLANE),CONDITION
      
904   format(I5,2X,I4,3X,A3,4X,'CH_TT',1X,F10.3,4X,E12.5,2X,F10.3,3X,E12.5,4X,A4)
      
      write(949,905)INDCHORD,NPLANE,NJOINT,SCFCHORDSADDLEJOINT_SS(INDEX,NPLANE),AHOTSPORTCHORDSADDLE_SS(INDEX,NPLANE),
     1 SCFCHORDCROWNJOINT_SS(INDEX,NPLANE),AHOTSPORTCHORDCROWN_SS(INDEX,NPLANE),CONDITION
      
905   format(I5,2X,I4,3X,A3,4X,'CH_SS',1X,F10.3,4X,E12.5,2X,F10.3,3X,E12.5,4X,A4)
      
      write(949,906)INDCHORD,NPLANE,NJOINT,AHOTSPORTCHORDSADDLE_MX(INDEX,NPLANE),
     1 AHOTSPORTCHORDCROWN_MX(INDEX,NPLANE),CONDITION
      
906   format(I5,2X,I4,3X,A3,4X,'CH_MX',4X,'COMBINE',4X,E12.5,5X,'COMBINE',3X,E12.5,4X,A4)
      
      !=================================
      ! EXCELL RESULT FORMAT
      !=================================
      
      !write(949,903)
      write(939,703)INDCHORD ,',',NPLANE ,',',NJOINT  , ',', ',',SCFCHORDSADDLEJOINT_AXIAL(INDEX,NPLANE),','
     1 ,AHOTSPORTCHORDSADDLE_AXIAL(INDEX,NPLANE) ,',', 
     1 SCFCHORDCROWNJOINT_AXIAL(INDEX,NPLANE),',',AHOTSPORTCHORDCROWN_AXIAL(INDEX,NPLANE) ,',',CONDITION
      
703   FORMAT (I5,A,I4 ,A,A3,A,'CH_AX',A,F10.3 ,A,E10.3 ,A ,F12.5 ,A, E12.5 ,A,A4)
      
      !write(949,904)
      write(939,704)INDCHORD,',',NPLANE,',',NJOINT, ',', ',',SCFCHORDSADDLEJOINT_TT(INDEX,NPLANE),','
     1 ,AHOTSPORTCHORDSADDLE_TT(INDEX,NPLANE),',', 
     1 SCFCHORDCROWNJOINT_TT(INDEX,NPLANE),',',AHOTSPORTCHORDCROWN_TT(INDEX,NPLANE),',',CONDITION
      
704   FORMAT (I5,A,I4 ,A,A3,A,'CH_TT',A,F10.3 ,A,E10.3 ,A ,F12.5 ,A, E12.5 ,A,A4)     
      
      !write(949,905)
      write(939,705)INDCHORD,',',NPLANE,',',NJOINT, ',', ',',SCFCHORDSADDLEJOINT_SS(INDEX,NPLANE),','
     1 ,AHOTSPORTCHORDSADDLE_SS(INDEX,NPLANE),',',
     1 SCFCHORDCROWNJOINT_SS(INDEX,NPLANE),',',AHOTSPORTCHORDCROWN_SS(INDEX,NPLANE),',',CONDITION
      
705   FORMAT (I5,A,I4 ,A,A3,A,'CH_SS',A,F10.3 ,A,E10.3 ,A ,F12.5 ,A, E12.5 ,A,A4)    
      
      !write(949,906)
      write(939,706)INDCHORD,',',NPLANE,',',NJOINT,',' ,',',',' , AHOTSPORTCHORDSADDLE_MX(INDEX,NPLANE),',',',' ,
     1 AHOTSPORTCHORDCROWN_MX(INDEX,NPLANE),',',CONDITION
      
706   FORMAT (I5,A,I4 ,A,A3,A,'CH_MX',A,'COMBINE',A ,E12.5 ,A,'COMBINE',A ,E12.5 ,A,A4)      
           
      
      !==========================================================================================================
      
      ENDSELECT
      

      ! HOTSPOT RESOULT
      write(948,907)INDCHORD,NPLANE,NJOINT,AHOTSPORTCHORDSADDLE_MX(INDEX,NPLANE),
     1 AHOTSPORTCHORDCROWN_MX(INDEX,NPLANE),CONDITION
      
907   format(I5,2X,I4,3X,A3,5X,'CHORD',3X,'COMBINE',4X,E12.5,5X,'COMBINE',3X,E12.5,4X,A4)

!====================================================================================================================
!===============   EXCELL RESULT
!====================================================================================================================
      
      write(938,937)INDCHORD,',',NPLANE ,',',NJOINT ,',' ,',',',' ,AHOTSPORTCHORDSADDLE_MX(INDEX,NPLANE) ,',',',' ,
     1 AHOTSPORTCHORDCROWN_MX(INDEX,NPLANE) ,',',CONDITION
      
937   FORMAT (I5,A,I4 ,A,A3,A,'CHORD' ,A,'COMBINE',A ,E12.5 ,A,'COMBINE',A ,E12.5 ,A,A4)
      
!====================================================================================================================
!====================================================================================================================

!      write(940,916)NNODE,TIME,NFATIGUELOOPOUT,INDCHORD,NPLANE,NJOINT,AHOTSPORTCHORDSADDLE_MX(INDEX,NPLANE),
!     1 AHOTSPORTCHORDCROWN_MX(INDEX,NPLANE)

916   format(I5,2X,F10.3,2X,I4,2X,I5,2X,I4,3X,A3,5X,'CHORD',2X,E12.5,2X,E12.5)
      
      write(960,716)NNODE,',',TIME,',',NFATIGUELOOPOUT,',',INDCHORD,',',NPLANE,',',NJOINT,',',',',
     1 AHOTSPORTCHORDSADDLE_MX(INDEX,NPLANE) ,',',AHOTSPORTCHORDCROWN_MX(INDEX,NPLANE)

716   format(I5,A,F10.3,A,I4,A,I5,A,I4,A,A3,A,'CHORD',A,E12.5,A,E12.5)            
            
      
!      NUMBERCHORD(INDEXSTORE) = NNCORD
!      NUMBERBRACE(INDEXSTORE) =  MN 
!      NUMBERNPLANE(INDEXSTORE) = NPLANE
!      INDEXSTORE = INDEXSTORE + 1
      
      ENDDO
      
      
10    DO INDEX = 1 ,MN !BRACE
      INDEBRACE = NELECAL(INDEX)
      
      IF (NNODE .EQ. 54 ) THEN
          
          CHANA = 3
          
          ENDIF
      
      !============================
      ! GETTING BRACE AXIAL FORCE
      !============================
      
      ABFXX = DESIGNAXIAL(INDEBRACE)
      ABFTT = DESIGNSHEART(INDEBRACE)
      ABFSS = DESIGNSHEARS(INDEBRACE)
      ABMTO = DESIGNTORSION(INDEBRACE)
      ABMTT = DESIGNMOMENTT(INDEBRACE)
      ABMSS = DESIGNMOMENTS(INDEBRACE)
      
      write(5001,5102)NNODE,INDEBRACE,'BRACE',NPLANE,ABFXX,ABFTT,ABFSS,ABMTO,ABMTT,ABMSS
5102  format(i6,3x,i6,3X,A5,6X,I1,1X,6E12.4,4X)      
      
      !============================
      ! BRACE PROPERTY CALCULATION
      !============================
      
      PI= 3.1416D0
      DIABRACE = BRACEDIAMETER(INDEX) 
      THICKBRACE = BRACETHICKNESS(INDEX)
      
      AREABRACE =  PI * (DIABRACE**4D0 - (DIABRACE-2D0*THICKBRACE)**4D0  ) / 4D0
      
      AMOMENTOFINTIA = PI * (DIABRACE**4D0 - (DIABRACE-2D0*THICKBRACE)**4D0  ) / 64D0
      
      !==================================
      ! HOTSPOT BRACE STRESS CALCULATION
      !==================================
      
      STRESSBFXX = ABFXX / AREABRACE
      STRESSBFTT = ABFTT / AREABRACE
      STRESSBFSS = ABFSS / AREABRACE 
      
      STRESSMTT  = ABMTT * 0.5D0 * DIABRACE   / AMOMENTOFINTIA
      STRESSMSS  = ABMSS * 0.5D0 * DIABRACE   / AMOMENTOFINTIA
      STRESSMTO  = ABMTO * 0.5D0 * DIABRACE   / (2*AMOMENTOFINTIA)
      
      write(5002,5102)NNODE,INDEBRACE,'BRACE',NPLANE,STRESSBFXX,STRESSBFTT,STRESSBFSS,STRESSMTO,STRESSMTT,STRESSMSS
      !TIMEDYNA
      
      TIMEDYNA = CTIM
      
      write(5012,5112)NNODE,INDEBRACE,'BRACE',NPLANE,TIMEDYNA,STRESSBFXX,STRESSBFTT,STRESSBFSS,STRESSMTO,STRESSMTT,STRESSMSS
5112  format(i6,3x,i6,3X,A5,6X,I1,1X,F10.3,6E12.4,4X)      
      
      StressPoint_1 = SCFBRACECROWNJOINT_AXIAL(INDEX,NPLANE) * STRESSBFXX
     1  + SCFBRACECROWNJOINT_SS(INDEX,NPLANE) * STRESSBFSS
      
      StressPoint_2 = 0.5d0*(SCFBRACECROWNJOINT_AXIAL(INDEX,NPLANE) * SCFBRACESADDLEJOINT_AXIAL(INDEX,NPLANE)) * STRESSBFXX
     1  + 0.5d0*1.4142135624d0* (SCFBRACECROWNJOINT_SS(INDEX,NPLANE)  ) * STRESSMSS
     1  - 0.5d0*1.4142135624d0* (SCFBRACESADDLEJOINT_TT(INDEX,NPLANE) ) * STRESSMTT
      
      StressPoint_3 = SCFBRACESADDLEJOINT_AXIAL(INDEX,NPLANE) * STRESSBFXX
     1  - SCFBRACESADDLEJOINT_TT(INDEX,NPLANE) * STRESSMTT
      
      StressPoint_4 = 0.5d0*(SCFBRACECROWNJOINT_AXIAL(INDEX,NPLANE) * SCFBRACESADDLEJOINT_AXIAL(INDEX,NPLANE)) * STRESSBFXX
     1  - 0.5d0*1.4142135624d0* (SCFBRACECROWNJOINT_SS(INDEX,NPLANE)  ) * STRESSMSS
     1  - 0.5d0*1.4142135624d0* (SCFBRACESADDLEJOINT_TT(INDEX,NPLANE) ) * STRESSMTT
      
      StressPoint_5 = SCFBRACECROWNJOINT_AXIAL(INDEX,NPLANE) * STRESSBFXX
     1  - (SCFBRACECROWNJOINT_SS(INDEX,NPLANE)  ) * STRESSMSS
      
      StressPoint_6 = 0.5d0*(SCFBRACECROWNJOINT_AXIAL(INDEX,NPLANE) * SCFBRACESADDLEJOINT_AXIAL(INDEX,NPLANE)) * STRESSBFXX
     1  - 0.5d0*1.4142135624d0* (SCFBRACECROWNJOINT_SS(INDEX,NPLANE)  ) * STRESSMSS
     1  + 0.5d0*1.4142135624d0* (SCFBRACESADDLEJOINT_TT(INDEX,NPLANE) ) * STRESSMTT
      
      StressPoint_7 = SCFBRACESADDLEJOINT_AXIAL(INDEX,NPLANE) * STRESSBFXX
     1  + SCFBRACESADDLEJOINT_TT(INDEX,NPLANE) * STRESSMTT
      
      StressPoint_8 = 0.5d0*(SCFBRACECROWNJOINT_AXIAL(INDEX,NPLANE) * SCFBRACESADDLEJOINT_AXIAL(INDEX,NPLANE)) * STRESSBFXX
     1  + 0.5d0*1.4142135624d0* (SCFBRACECROWNJOINT_SS(INDEX,NPLANE)  ) * STRESSMSS
     1  + 0.5d0*1.4142135624d0* (SCFBRACESADDLEJOINT_TT(INDEX,NPLANE) ) * STRESSMTT
      
      AHOTSPOT_BRACE(1) = ABS( StressPoint_1 )
      AHOTSPOT_BRACE(2) = ABS( StressPoint_2 )
      AHOTSPOT_BRACE(3) = ABS( StressPoint_3 )
      AHOTSPOT_BRACE(4) = ABS( StressPoint_4 )
      AHOTSPOT_BRACE(5) = ABS( StressPoint_5 )
      AHOTSPOT_BRACE(6) = ABS( StressPoint_6 )
      AHOTSPOT_BRACE(7) = ABS( StressPoint_7 )
      AHOTSPOT_BRACE(8) = ABS( StressPoint_8 )
      
      AMAXHOTSOPT = MAXVAL( abs(AHOTSPOT_BRACE) )
      
      write(5004,5104)NNODE,INDEBRACE,'BRACE',NPLANE,StressPoint_1 , StressPoint_2, StressPoint_3, StressPoint_4,StressPoint_5
     1 ,StressPoint_6 , StressPoint_7, StressPoint_8
      
      write(5016,5104)NNODE,INDEBRACE,'BRACE',NPLANE,StressPoint_1 , StressPoint_2, StressPoint_3, StressPoint_4,StressPoint_5
     1 ,StressPoint_6 , StressPoint_7, StressPoint_8
      
5104  format(i6,3x,i6,3X,A5,6X,I1,1X,8E12.4)   
      
      DO I = 1,8 
         
          IF( AHOTSPOT_BRACE(1) .EQ. AMAXHOTSOPT ) HOPPOSITION = 'T'
          IF( AHOTSPOT_BRACE(2) .EQ. AMAXHOTSOPT ) HOPPOSITION = 'TR'
          IF( AHOTSPOT_BRACE(3) .EQ. AMAXHOTSOPT ) HOPPOSITION = 'R'
          IF( AHOTSPOT_BRACE(4) .EQ. AMAXHOTSOPT ) HOPPOSITION = 'BR'
          IF( AHOTSPOT_BRACE(5) .EQ. AMAXHOTSOPT ) HOPPOSITION = 'B'
          IF( AHOTSPOT_BRACE(6) .EQ. AMAXHOTSOPT ) HOPPOSITION = 'BL'
          IF( AHOTSPOT_BRACE(7) .EQ. AMAXHOTSOPT ) HOPPOSITION = 'L'
          IF( AHOTSPOT_BRACE(8) .EQ. AMAXHOTSOPT ) HOPPOSITION = 'TL'
          
      ENDDO
      
      if(KFTTD.eq.1)  TIME = CTIM
      
!      write(5005,5105)NNODE,INDEBRACE,'BRACE',NPLANE,HOPPOSITION,AMAXHOTSOPT

!5105  format(i6,3x,i6,3X,A5,6X,I1,6X,A2,8E12.4)   
      
      write(5005,5105)NNODE,TIME,NFATIGUELOOPOUT,INDEBRACE,NPLANE,NJOINT,HOPPOSITION,AMAXHOTSOPT
      
      write(5017,5105)NNODE,TIME,NFATIGUELOOPOUT,INDEBRACE,NPLANE,NJOINT,HOPPOSITION,AMAXHOTSOPT

      
      
      write(940,5917)NNODE,TIME,NFATIGUELOOPOUT,INDEBRACE,NPLANE,NJOINT, HOPPOSITION ,
     1   AMAXHOTSOPT

5917  format(I5,2X,F10.3,2X,I4,2X,I5,2X,I4,3X,A3,5X,'BRACE',2X,A2,2X,E12.5)     
      
      
5105  format(I5,2X,F10.3,2X,I4,2X,I5,2X,I4,5X,A3,5X,'BRACE',2X,A2,2X,E12.5)   
      
      CHANA = 3      
      
      
       !============================
      
      
      
      !SCFCHORD
      
      StressPoint_1 = SCFCHORDCROWNJOINT_AXIAL(INDEX,NPLANE) * STRESSBFXX
     1  + SCFCHORDCROWNJOINT_SS(INDEX,NPLANE) * STRESSBFSS
      
      StressPoint_2 = 0.5d0*(SCFCHORDCROWNJOINT_AXIAL(INDEX,NPLANE) * SCFCHORDSADDLEJOINT_AXIAL(INDEX,NPLANE)) * STRESSBFXX
     1  + 0.5d0*1.4142135624d0* (SCFCHORDCROWNJOINT_SS(INDEX,NPLANE)  ) * STRESSMSS
     1  - 0.5d0*1.4142135624d0* (SCFCHORDSADDLEJOINT_TT(INDEX,NPLANE) ) * STRESSMTT
      
      StressPoint_3 = SCFCHORDSADDLEJOINT_AXIAL(INDEX,NPLANE) * STRESSBFXX
     1  - SCFCHORDSADDLEJOINT_TT(INDEX,NPLANE) * STRESSMTT
      
      StressPoint_4 = 0.5d0*(SCFCHORDCROWNJOINT_AXIAL(INDEX,NPLANE) * SCFCHORDSADDLEJOINT_AXIAL(INDEX,NPLANE)) * STRESSBFXX
     1  - 0.5d0*1.4142135624d0* (SCFCHORDCROWNJOINT_SS(INDEX,NPLANE)  ) * STRESSMSS
     1  - 0.5d0*1.4142135624d0* (SCFCHORDSADDLEJOINT_TT(INDEX,NPLANE) ) * STRESSMTT
      
      StressPoint_5 = SCFCHORDCROWNJOINT_AXIAL(INDEX,NPLANE) * STRESSBFXX
     1  - (SCFCHORDCROWNJOINT_SS(INDEX,NPLANE)  ) * STRESSMSS
      
      StressPoint_6 = 0.5d0*(SCFCHORDCROWNJOINT_AXIAL(INDEX,NPLANE) * SCFCHORDSADDLEJOINT_AXIAL(INDEX,NPLANE)) * STRESSBFXX
     1  - 0.5d0*1.4142135624d0* (SCFCHORDCROWNJOINT_SS(INDEX,NPLANE)  ) * STRESSMSS
     1  + 0.5d0*1.4142135624d0* (SCFCHORDSADDLEJOINT_TT(INDEX,NPLANE) ) * STRESSMTT
      
      StressPoint_7 = SCFCHORDSADDLEJOINT_AXIAL(INDEX,NPLANE) * STRESSBFXX
     1  + SCFCHORDSADDLEJOINT_TT(INDEX,NPLANE) * STRESSMTT
      
      StressPoint_8 = 0.5d0*(SCFCHORDCROWNJOINT_AXIAL(INDEX,NPLANE) * SCFCHORDSADDLEJOINT_AXIAL(INDEX,NPLANE)) * STRESSBFXX
     1  + 0.5d0*1.4142135624d0* (SCFCHORDCROWNJOINT_SS(INDEX,NPLANE)  ) * STRESSMSS
     1  + 0.5d0*1.4142135624d0* (SCFCHORDSADDLEJOINT_TT(INDEX,NPLANE) ) * STRESSMTT
      
           
      AHOTSPOT_CHORD(1) = ABS( StressPoint_1 )
      AHOTSPOT_CHORD(2) = ABS( StressPoint_2 )
      AHOTSPOT_CHORD(3) = ABS( StressPoint_3 )
      AHOTSPOT_CHORD(4) = ABS( StressPoint_4 )
      AHOTSPOT_CHORD(5) = ABS( StressPoint_5 )
      AHOTSPOT_CHORD(6) = ABS( StressPoint_6 )
      AHOTSPOT_CHORD(7) = ABS( StressPoint_7 )
      AHOTSPOT_CHORD(8) = ABS( StressPoint_8 )
      
      AMAXHOTSOPT = MAXVAL( AHOTSPOT_CHORD )
      
      DO I = 1,8 
         
          IF( AHOTSPOT_CHORD(1) .EQ. AMAXHOTSOPT ) HOPPOSITION = 'T'
          IF( AHOTSPOT_CHORD(2) .EQ. AMAXHOTSOPT ) HOPPOSITION = 'TR'
          IF( AHOTSPOT_CHORD(3) .EQ. AMAXHOTSOPT ) HOPPOSITION = 'R'
          IF( AHOTSPOT_CHORD(4) .EQ. AMAXHOTSOPT ) HOPPOSITION = 'BR'
          IF( AHOTSPOT_CHORD(5) .EQ. AMAXHOTSOPT ) HOPPOSITION = 'B'
          IF( AHOTSPOT_CHORD(6) .EQ. AMAXHOTSOPT ) HOPPOSITION = 'BL'
          IF( AHOTSPOT_CHORD(7) .EQ. AMAXHOTSOPT ) HOPPOSITION = 'L'
          IF( AHOTSPOT_CHORD(8) .EQ. AMAXHOTSOPT ) HOPPOSITION = 'TL'
          
      ENDDO
      
      write(5004,5104)NNODE,INDEBRACE,'CHORD',NPLANE,StressPoint_1 , StressPoint_2, StressPoint_3, StressPoint_4,StressPoint_5
     1 ,StressPoint_6 , StressPoint_7, StressPoint_8
      
      write(5016,5104)NNODE,INDEBRACE,'CHORD',NPLANE,StressPoint_1 , StressPoint_2, StressPoint_3, StressPoint_4,StressPoint_5
     1 ,StressPoint_6 , StressPoint_7, StressPoint_8
      
      write(940,5918)NNODE,TIME,NFATIGUELOOPOUT,INDEBRACE,NPLANE,NJOINT,  HOPPOSITION , AMAXHOTSOPT

5918  format(I5,2X,F10.3,2X,I4,2X,I5,2X,I4,3X,A3,5X,'CHORD',2X,A2,2X,E12.5)         
      
      
      if(KFTTD.eq.1)  TIME = CTIM
!      write(5005,5105)NNODE,INDEBRACE,'BRACE',NPLANE,HOPPOSITION,AMAXHOTSOPT

!5105  format(i6,3x,i6,3X,A5,6X,I1,6X,A2,8E12.4)   
      
      write(5005,5106)NNODE,TIME,NFATIGUELOOPOUT,INDEBRACE,NPLANE,NJOINT,HOPPOSITION,AMAXHOTSOPT
      write(5017,5106)NNODE,TIME,NFATIGUELOOPOUT,INDEBRACE,NPLANE,NJOINT,HOPPOSITION,AMAXHOTSOPT
      
5106  format(I5,2X,F10.3,2X,I4,2X,I5,2X,I4,5X,A3,5X,'CHORD',2X,A2,2X,E12.5)         
      
      
      
      
      SELECTCASE(CONDITION)

      CASE('MANL')
          
          SAFXBS1 = SCFBRACESADDLEMANL_A(NUMBEROFJOINT,INDEX,NPLANE) ! FOR CHECKING
          SAFXBC1 = SCFBRACECROWNMANL_A(NUMBEROFJOINT,INDEX,NPLANE)  ! FOR CHECKING
          
          write(9970,*) STRESSBFXX , STRESSBFXX
          
      AHOTSPORTBRACESADDLE(INDEX,NPLANE) = STRESSBFXX * 1 ! SCFBRACESADDLEMANL_A(NUMBEROFJOINT,NPLANE,INDEX)
      AHOTSPORTBRACECROWN(INDEX,NPLANE)  = STRESSBFXX * 1 ! SCFBRACECROWNMANL_A(NUMBEROFJOINT,NPLANE,INDEX)
      
      AHOTSPORTBRACESADDLE_TT(INDEX,NPLANE) = STRESSMTT * 0D0 !
      AHOTSPORTBRACECROWN_TT(INDEX,NPLANE)  = STRESSMTT * 0D0 !
      
      AHOTSPORTBRACESADDLE_SS(INDEX,NPLANE) = STRESSMSS * 0D0 !
      AHOTSPORTBRACECROWN_SS(INDEX,NPLANE)  = STRESSMSS * 0D0 !
      
      !=================================
      ! STRESS SUPERPOSITION
      !=================================
      
      AHOTSPORTBRACESADDLE_MX(INDEX,NPLANE) = AHOTSPORTBRACESADDLE(INDEX,NPLANE) +
     1   AHOTSPORTBRACESADDLE_TT(INDEX,NPLANE)  +  AHOTSPORTBRACESADDLE_SS(INDEX,NPLANE)

      
      AHOTSPORTBRACECROWN_MX(INDEX,NPLANE)  =  AHOTSPORTBRACECROWN(INDEX,NPLANE)  +
     1   AHOTSPORTBRACECROWN_TT(INDEX,NPLANE)   +   AHOTSPORTBRACECROWN_SS(INDEX,NPLANE)
          
      
      CASE('AUTO')   
          
            write(9970,*) STRESSBFXX , STRESSBFXX, 'AUTO'
      
      AHOTSPORTBRACESADDLE(INDEX,NPLANE) = STRESSBFXX * SCFBRACESADDLEJOINT_AXIAL(INDEX,NPLANE)
      AHOTSPORTBRACECROWN(INDEX,NPLANE)  = STRESSBFXX * SCFBRACECROWNJOINT_AXIAL(INDEX,NPLANE)
      
      AHOTSPORTBRACESADDLE_TT(INDEX,NPLANE) = STRESSMTT * SCFBRACESADDLEJOINT_TT(INDEX,NPLANE)
      AHOTSPORTBRACECROWN_TT(INDEX,NPLANE)  = STRESSMTT * SCFBRACECROWNJOINT_TT(INDEX,NPLANE)
      
      AHOTSPORTBRACESADDLE_SS(INDEX,NPLANE) = STRESSMSS * SCFBRACESADDLEJOINT_SS(INDEX,NPLANE)
      AHOTSPORTBRACECROWN_SS(INDEX,NPLANE)  = STRESSMSS * SCFBRACECROWNJOINT_SS(INDEX,NPLANE)
      
      chana = 3
      
      
      AAHOTCHORDSADDLEJOINT = STRESSBFXX * SCFCHORDSADDLEJOINT_AXIAL(INDEX,NPLANE) + STRESSMTT *SCFCHORDSADDLEJOINT_TT(INDEX,NPLANE)
      AAHOTCHORDCROWNJOINT  = STRESSBFXX * SCFCHORDCROWNJOINT_AXIAL (INDEX,NPLANE) + STRESSMSS *SCFCHORDCROWNJOINT_SS(INDEX,NPLANE)
      
      AAHOTBRACESADDLEJOINT = STRESSBFXX * SCFBRACESADDLEJOINT_AXIAL(INDEX,NPLANE) + STRESSMTT *SCFBRACESADDLEJOINT_TT(INDEX,NPLANE)
      AAHOTBRACECROWNJOINT  = STRESSBFXX * SCFBRACECROWNJOINT_AXIAL (INDEX,NPLANE) + STRESSMTT *SCFBRACESADDLEJOINT_TT(INDEX,NPLANE)
      
!      WRITE(5000,5009)STRESSBFXX,STRESSMTT,STRESSMSS
5009  FORMAT(4E19.4)  
            
!      WRITE(5000,5001)AAHOTCHORDSADDLEJOINT,AAHOTCHORDCROWNJOINT,AAHOTBRACESADDLEJOINT,AAHOTBRACECROWNJOINT
5001  FORMAT(4E19.4)      
!         STRESSBFXX * SCFCHORDSADDLEJOINT_AXIAL(I,NPLANE)
!         STRESSBFXX * SCFCHORDCROWNJOINT_AXIAL (I,NPLANE)
!         STRESSBFXX * SCFBRACESADDLEJOINT_AXIAL(I,NPLANE)
!         STRESSBFXX * SCFBRACECROWNJOINT_AXIAL (I,NPLANE)
!         
!         STRESSMSS * SCFCHORDCROWNJOINT_SS(I,NPLANE)
!         STRESSMSS * SCFBRACECROWNJOINT_SS(I,NPLANE)
!          
!         STRESSMTT * SCFCHORDSADDLEJOINT_TT(I,NPLANE)
!         STRESSMTT * SCFBRACESADDLEJOINT_TT(I,NPLANE)
      
       
      
      
      
      !=================================
      ! STRESS SUPERPOSITION
      !=================================
      
      AHOTSPORTBRACESADDLE_MX(INDEX,NPLANE) = AHOTSPORTBRACESADDLE(INDEX,NPLANE) +
     1   AHOTSPORTBRACESADDLE_TT(INDEX,NPLANE)  +  AHOTSPORTBRACESADDLE_SS(INDEX,NPLANE)

      
      AHOTSPORTBRACECROWN_MX(INDEX,NPLANE)  =  AHOTSPORTBRACECROWN(INDEX,NPLANE)  +
     1   AHOTSPORTBRACECROWN_TT(INDEX,NPLANE)   +   AHOTSPORTBRACECROWN_SS(INDEX,NPLANE)
      
      !==========================================================================================
      ! DNV Suberposition
      !==========================================================================================
      
     
      
      
      write(949,902)INDEBRACE,NPLANE,NJOINT , SCFBRACESADDLEJOINT_AXIAL(INDEX,NPLANE),
     1 AHOTSPORTBRACESADDLE(INDEX,NPLANE), SCFBRACECROWNJOINT_AXIAL(INDEX,NPLANE),AHOTSPORTBRACECROWN(INDEX,NPLANE),CONDITION

902   format(I5,2X,I4,3X,A3,4X,'BR_AX',1X,F10.3,4X,E12.5,2X,F10.3,3X,E12.5,4X,A4)
      
      write(949,912)INDEBRACE,NPLANE,NJOINT, SCFBRACESADDLEJOINT_TT(INDEX,NPLANE),
     1 AHOTSPORTBRACESADDLE_TT(INDEX,NPLANE), SCFBRACECROWNJOINT_TT(INDEX,NPLANE),AHOTSPORTBRACECROWN_TT(INDEX,NPLANE),CONDITION 
      
912   format(I5,2X,I4,3X,A3,4X,'BR_TT',1X,F10.3,4X,E12.5,2X,F10.3,3X,E12.5,4X,A4)     
      
       write(949,913)INDEBRACE,NPLANE,NJOINT, SCFBRACESADDLEJOINT_SS(INDEX,NPLANE),
     1 AHOTSPORTBRACESADDLE_SS(INDEX,NPLANE), SCFBRACECROWNJOINT_SS(INDEX,NPLANE),AHOTSPORTBRACECROWN_SS(INDEX,NPLANE),CONDITION 
      
913   format(I5,2X,I4,3X,A3,4X,'BR_SS',1X,F10.3,4X,E12.5,2X,F10.3,3X,E12.5,4X,A4)     
      
       write(949,914)INDEBRACE,NPLANE,NJOINT, AHOTSPORTBRACESADDLE_MX(INDEX,NPLANE) ,
     1   AHOTSPORTBRACECROWN_MX(INDEX,NPLANE),CONDITION
      
914   format(I5,2X,I4,3X,A3,4X,'BR_MX',4X,'COMBINE',4X,E12.5,5X,'COMBINE',3X,E12.5,4X,A4)
      
      
      !=================================
      ! EXCELL RESULT FORMAT
      !=================================
      
      !write(949,902)
      write(939,711)INDEBRACE ,',',NPLANE,',', NJOINT , ',', ',', SCFBRACESADDLEJOINT_AXIAL(INDEX,NPLANE),',',
     1 AHOTSPORTBRACESADDLE(INDEX,NPLANE),','
     1 ,SCFBRACECROWNJOINT_AXIAL(INDEX,NPLANE),',',AHOTSPORTBRACECROWN(INDEX,NPLANE),',',CONDITION
      
711   FORMAT (I5,A,I4 ,A,A3,A,'BR_AX',A,F10.3 ,A,E10.3 ,A ,F12.5 ,A, E12.5 ,A,A4)      
      
      write(939,712)INDEBRACE,',',NPLANE,',',NJOINT, ',', ',',  SCFBRACESADDLEJOINT_TT(INDEX,NPLANE),',',
     1 AHOTSPORTBRACESADDLE_TT(INDEX,NPLANE),','
     1 ,SCFBRACECROWNJOINT_TT(INDEX,NPLANE),',',AHOTSPORTBRACECROWN_TT(INDEX,NPLANE),',',CONDITION 
      
712   FORMAT (I5,A,I4 ,A,A3,A,'BR_TT',A,F10.3 ,A,E10.3 ,A ,F12.5 ,A, E12.5 ,A,A4)             
      
      write(939,713)INDEBRACE,',',NPLANE,',',NJOINT, ',', ',', SCFBRACESADDLEJOINT_SS(INDEX,NPLANE),',',
     1 AHOTSPORTBRACESADDLE_SS(INDEX,NPLANE),','
     1 , SCFBRACECROWNJOINT_SS(INDEX,NPLANE),',',AHOTSPORTBRACECROWN_SS(INDEX,NPLANE),',',CONDITION 
          
713   FORMAT (I5,A,I4 ,A,A3,A,'BR_SS',A,F10.3 ,A,E10.3 ,A ,F12.5 ,A, E12.5 ,A,A4)          
      
       write(939,714)INDEBRACE,',',NPLANE,',',NJOINT,',' ,',',',' , AHOTSPORTBRACESADDLE_MX(INDEX,NPLANE),',',',' ,
     1   AHOTSPORTBRACECROWN_MX(INDEX,NPLANE),',',CONDITION
      
714   FORMAT (I5,A,I4 ,A,A3,A,'BR_MX',A,'COMBINE',A ,E12.5 ,A,'COMBINE',A ,E12.5 ,A,A4)   
      
      
      
      ENDSELECT
      
      ! HOTSPOT DATA
      
      write(948,915)INDEBRACE,NPLANE,NJOINT, AHOTSPORTBRACESADDLE_MX(INDEX,NPLANE) ,
     1   AHOTSPORTBRACECROWN_MX(INDEX,NPLANE),CONDITION
       
915   format(I5,2X,I4,3X,A3,5X,'BRACE',3X,'COMBINE',4X,E12.5,5X,'COMBINE',3X,E12.5,4X,A4)
      
    
      !HOTSPOT EXCELL RESULT

      write(938,935)INDEBRACE,',',NPLANE,',',NJOINT,',' ,',',',' , AHOTSPORTBRACESADDLE_MX(INDEX,NPLANE) ,',',',' ,
     1   AHOTSPORTBRACECROWN_MX(INDEX,NPLANE),',',CONDITION
            
935   FORMAT (I5,A,I4 ,A,A3,A,'BRACE' ,A,'COMBINE',A ,E12.5 ,A,'COMBINE',A ,E12.5 ,A,A4)
      
!====================================================================================================================
!====================================================================================================================
      
!      write(940,917)NNODE,TIME,NFATIGUELOOPOUT,INDEBRACE,NPLANE,NJOINT, AHOTSPORTBRACESADDLE_MX(INDEX,NPLANE) ,
!     1   AHOTSPORTBRACECROWN_MX(INDEX,NPLANE) chana
           
      
           
917   format(I5,2X,F10.3,2X,I4,2X,I5,2X,I4,3X,A3,5X,'BRACE',2X,E12.5,2X,E12.5)   
      
      

      
      
      write(960,717)NNODE,',',TIME,',',NFATIGUELOOPOUT,',',INDEBRACE,',',NPLANE,',',NJOINT,',',',',  
     1 AHOTSPORTBRACESADDLE_MX(INDEX,NPLANE) ,',', AHOTSPORTBRACECROWN_MX(INDEX,NPLANE)
      
717   format(I5,A,F10.3,A,I4,A,I5,A,I4,A,A3,A,'BRACE',A,E12.5,A,E12.5)        
      
!      write(960,716)NNODE,',',TIME,',',NFATIGUELOOPOUT,',',INDCHORD,',',NPLANE,',',NJOINT,',',',',
!     1 AHOTSPORTCHORDSADDLE_MX(INDEX,NPLANE) ,',',AHOTSPORTCHORDCROWN_MX(INDEX,NPLANE)

!716   format(I5,A,F10.3,A,I4,A,I5,A,I4,A,A3,A,'CHORD',A,E12.5,A,E12.5)     
      
      JCHANA = JCHANA + 1
      
 !     NUMBERCHORD(INDEXSTORE) = NNCORD
 !     NUMBERBRACE(INDEXSTORE) = MN 
 !     NUMBERNPLANE(INDEXSTORE) = NPLANE
      INDEXSTORE = INDEXSTORE + 1
      
       ENDDO
       Nheaderinnitialjointfatigue = 2D0

      RETURN 
      END SUBROUTINE MAXSTRESSCALCULATION
!=====================================================================================================================================
      
      
      
      
!=====================================================================================================================================
!=====================================================================================================================================
! FATIGUE JOING ANALYSIS
!=====================================================================================================================================      
!=====================================================================================================================================
      subroutine JOINTFATIGUE
      
      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT INTEGER*4 (i-n)
      CHARACTER*5 JOINTTYPE , MEMBER   
      CHARACTER*6 DPOSITION
      CHARACTER*2 HOPPOSITION
      
      
      COMMON /INPUTJOINT/ NNODEJOINT(1000),JOINTCASE(1000),SAFTYFACTOR(1000),DESIGNLIFE(1000),GAP_JOINT(1000),JOINTLOOP
      COMMON /JOINTMANUAL/ NNODEJOINTM(1000),NNPLANE(1000),SCFCHORDCROWN(1000),SCFCHORDSADDLE(1000),SCFACROWN(1000),SCFBCROWN(1000)
     1                    ,SCFCCROWN(1000),SCFASADDLE(1000),SCFBCSADDLE(1000),SCFCSADDLE(1000),JOINTLOOPMANUAL
      COMMON /FATIGUE_OFFSHORE/ NWAVESCAT, NWINDSCAT
      COMMON /WAVE_SCATTER/ NUMSCAT(1000),HSCAT(1000),PERIODSCAT(1000),AMENITUDESCAT(1000)
      COMMON /KEEP_HOTDATA_REAL/ AHOTSPOT(200000) , FREQX(200000) , SADDL_HOT(200000),CROWN_HOT(200000)
      COMMON /KEEP_HOTDATA_INTEGER/ NNODEX(200000) , NJOINT(200000) , NSCTLOOP(200000)
      COMMON /MOMENTSPECTYRUM/ AZEROMOMENTSADDLE(200000), AZEROMOMENTCROWN(200000),AZEROMOMENTHOTSPOT(200000)
     1                        , ASECONDMOMENTSADDLE(200000), ASECONDMOMENTCROWN(200000),ASECONDMOMENTHOTSPOT(200000)
     1                        , TTZHOTSPOT(200000) , TTZSADDLE(200000) , TTZCROWN(200000)  ,NODESPEC(200000),NLOOPX(200000),
     1            EFFSTRESSSADDLE(200000), EFFSTRESSCROWN(200000),
     1            SADDLEDAMAGE(200000),CROWNDAMAGE(200000),AHOTSPOTDAMAGE(200000),
     1            TOTALSADDLEDAMAGE(200000),TOTALCROWNDAMAGE(200000),TOTALHOTSPOTDAMAGE(200000)
         
      COMMON /LINEAT/ KTRAF,KEATH,KCSAL,KOFFL,KSPEC,KDESIGN,KFATM,KFATJ,KFATL,KFAST,KOREV
      COMMON /INOU/ ITI,ITO,ISO,NDATI,NPLOT,NKFAC,NELEM,IFPR(10),IFPL(10)
      COMMON /ChanaSpectrum/ Start , AInterval , Aend   !Chana 2014 RESPONSE SPECTRUM FOR ISOLOP 1
      COMMON /ChanaTImeSeries/ DT  
      COMMON /S_N_CURVE_JOINT/ AMATERIAL_JOINT, BMMATERIAL_JOINT,STRESSEDURANCE_JOINT,CPAMETER_JOINT,RPARAMETER_JOINT             
      COMMON /DAMAGEFACTOR/ ALOCAL_EXPFACTOR(1000),DAMAGEDESIGNFACTOR(1000)
      
      CALL OFFSHSTEP(TIME,ITIME,NTIME,'CALT')   !CALT
      
      CALL OFFSHSTEP(TIMESTART,1,NTIME,'CALL')
      
      REWIND(940)
      
      READ(940,*)
      
      WRITE(930,*)'JONT_NUMB   FREQ   LOOP CONNECTIVITY TYPE    MEMBER LOC     HOTSPOT'
      
      INDEX = 1D0
      
      NTRYLOOP = JOINTLOOP + JOINTLOOPMANUAL   
      
      
      
      DO I = 1,NTRYLOOP*5*2   
          
           READ(940,10) NNODE,FREQ,LOOP,NCON1,NCON2,JOINTTYPE,MEMBER,HOPPOSITION,AHOTSPOTi
!10         format(I5,2X,F10.3,2X,I4,2X,I5,2X,I4,3X,A3,5X,A5,2X,E12.5,2X,E12.5,2X,I5)    
           
10     format(I5,2X,F10.3,2X,I4,2X,I5,2X,I4,3X,A3,5X,A5,2X,A2,2X,E12.5)   
           
      
           
      IF ( FREQ .GT. TIMESTART ) GOTO 200 
          
           WRITE(930,20)NNODE,FREQ,LOOP,NCON1,NCON2,JOINTTYPE,MEMBER,HOPPOSITION,AHOTSPOTi,INDEX
!20         format(I5,2X,F10.3,2X,I4,2X,I5,2X,I4,3X,A3,5X,A5,2X,E12.5,2X,E12.5,2X,I5)   
20         format(I5,2X,F10.3,2X,I4,2X,I5,2X,I4,3X,A3,5X,A5,2X,A2,2X,E12.5,2X,I5)   
          INDEX  = INDEX + 1D0 
          
      ENDDO
      
200   CONTINUE     
      
     

      IDATA = INDEX - 1
      
      !============================================================
      ! STRESS SPECTRUM  EACH
      !============================================================
      
      REWIND(940)
    
      
      INDEX = 1
      
      READ(940,*)
      
     
      !=====================
      ! READ HOTSPOT STRESS
      !=====================
      
      DO K = 1,NWAVESCAT
          DO J = 1,NTIME
              DO I = 1,IDATA
               
       READ(940,10) NNODEX(INDEX),FREQX(INDEX),NSCTLOOP(INDEX),NCON1,NCON2,JOINTTYPE,MEMBER,HOPPOSITION,AHOTSPOT(INDEX)
                          
                   INDEX = INDEX + 1
                   
              ENDDO
          ENDDO
      ENDDO
      
            
      
      
      !=============================
      ! MAKEING STRESS SPECTRM 
      !=============================
   
      WRITE(931,*)' NUM  INDEX     FREQUENCY  JOINT   LOOP   HOTSPOT_STRESS '
      
      WRITE(981,7981)',',',',',',',',',',','
7981   format(' NUM ',A,' INDEX  ',A,'    FREQUENCY  ',A,' JOINT  ',A,' LOOP  ',A,' SADDL_HOTSPOT  ',A,' CROWN_HOTSPOT' )      
      
      ICOUNT = 1D0
      
      DO K = 1,NWAVESCAT
          
          DO J = 1,IDATA
              
              DO I = 1, NTIME
                   
                  ISPEC =  ((I-1)*IDATA ) + J  + ( K-1 )*IDATA * NTIME
                   
          !WRITE(931,12) ICOUNT,ISPEC,FREQX(ISPEC),NNODEX(ISPEC), NSCTLOOP(ISPEC),SADDL_HOT(ISPEC),AHOTSPOT(ISPEC)
                  
                  WRITE(931,12) ICOUNT,ISPEC,FREQX(ISPEC),NNODEX(ISPEC), NSCTLOOP(ISPEC),AHOTSPOT(ISPEC)
                    
!12        FORMAT(I5,2X,I7,2X,f10.3,2X,I5,2X,I5,2X,E12.5,2X,E12.5)
12        FORMAT(I5,2X,I7,2X,f10.3,2X,I5,2X,I5,4X,E12.5,6X,E12.5)
          
!          WRITE(981,7812) ICOUNT,',',ISPEC,',',FREQX(ISPEC),',',NNODEX(ISPEC),',', NSCTLOOP(ISPEC),',',
!     1        SADDL_HOT(ISPEC),',',CROWN_HOT(ISPEC)
!
!7812        FORMAT(I5,A,I5,A,f10.3,A,I5,A,I5,A,E12.5,A,E12.5)

                   
              ENDDO
          ENDDO
      ENDDO
      
      !========================================
      ! READ SPECTRUM DATA FOR MOMENT SPECTRUM
      !========================================
      
     
      
      REWIND(931)
      
      INDEX = 1D0
      
      READ(931,*)
      
       DO K = 1,NWAVESCAT
          DO J = 1,NTIME
              DO I = 1,IDATA
               
        READ(931,12) ICOUNT,ISPEC,FREQX(INDEX),NNODEX(INDEX), NSCTLOOP(INDEX),AHOTSPOT(INDEX)               !SADDL_HOT(INDEX),CROWN_HOT(INDEX)

                   INDEX = INDEX + 1D0
                   
              ENDDO
          ENDDO
       ENDDO
       
       CHANAKEEPHOTSPORTDATA = 1
   
        
      !===============================
      !  MOMENT SPECTRUM CALCULATION
      !===============================
       
       WRITE(932,202)
!202    FORMAT('NUM    JOINT  NSCAT     SADDLE_m0        CROWN_m0       Tz      SADDLE_m2      CROWN_m2        TZ')
202    FORMAT('NUM    JOINT  NSCAT        m_0          m_2             Tz     ')
       
      WRITE(982,9202)',',',',',',',',',',',',',',','
9202  FORMAT('NUM ',A,'JOINT',A,'NSCAT',A,'SADDLE_m0',A,'CROWN_m0',A,'Tz',A,'SADDLE_m2',A,'CROWN_m2',A,'TZ')
       
       DO J = 1, IDATA * NWAVESCAT
           
          AMOMENTZERO_SADDL = 0D0
          AMOMENTZERO_CROWN = 0D0
          AMOMENTZERO_HOTSPOT = 0D0
          
          AMOMENTSECOND_SADDL = 0D0
          AMOMENTSECOND_CROWN = 0D0
          AMOMENTSECOND_HOTSPOT = 0D0
          
          DO I = 1,NTIME
          
          INDEX = I + (J-1)*NTIME
          
          !!!! ZERO MOMENT
          
          !AMOMENTZERO_SADDLi = AInterval * SADDL_HOT(INDEX)
          !AMOMENTZERO_CROWNi = AInterval * CROWN_HOT(INDEX)
          AMOMENTZERO_HOTSPOTi = AInterval * AHOTSPOT(INDEX)
          
          
          !AMOMENTZERO_SADDL = AMOMENTZERO_SADDL + AMOMENTZERO_SADDLi 
          !AMOMENTZERO_CROWN = AMOMENTZERO_CROWN + AMOMENTZERO_CROWNi
          AMOMENTZERO_HOTSPOT = AMOMENTZERO_HOTSPOT + AMOMENTZERO_HOTSPOTi
          
          !AZEROMOMENTSADDLE(J) = AMOMENTZERO_SADDL
          !AZEROMOMENTCROWN(J)  = AMOMENTZERO_CROWN
          AZEROMOMENTHOTSPOT(J)  = AMOMENTZERO_HOTSPOT
          
          
          
          !!!!SECONE MOMENT
          
          !AMOMENTSECOND_SADDLi = AInterval * ( FREQX(INDEX)**2D0 ) * SADDL_HOT(INDEX)
          !AMOMENTSECOND_CROWNi = AInterval * ( FREQX(INDEX)**2D0 ) * CROWN_HOT(INDEX)
          AMOMENTSECOND_HOTSPOTi = AInterval * ( FREQX(INDEX)**2D0 ) * AHOTSPOT(INDEX)
          
          !AMOMENTSECOND_SADDL = AMOMENTSECOND_SADDL + AMOMENTSECOND_SADDLi 
          !AMOMENTSECOND_CROWN = AMOMENTSECOND_CROWN + AMOMENTSECOND_CROWNi
          AMOMENTSECOND_HOTSPOT = AMOMENTSECOND_HOTSPOT + AMOMENTSECOND_HOTSPOTi
          
          !ASECONDMOMENTSADDLE(J) = AMOMENTSECOND_SADDL
          !ASECONDMOMENTCROWN(J)  = AMOMENTSECOND_CROWN
          ASECONDMOMENTHOTSPOT(J)  = AMOMENTSECOND_HOTSPOT
          
          NODESPEC(J)    = NNODEX(INDEX)
          NLOOPX(J)      = NSCTLOOP(INDEX)
          
           CHANZXX=3
          

          ENDDO
          
          !TTZSADDLE(J) = SQRT( AZEROMOMENTSADDLE(J) / ASECONDMOMENTSADDLE(J) )
          !TTZCROWN(J)  = SQRT( AZEROMOMENTCROWN(J) /  ASECONDMOMENTCROWN(J)  )
          TTZHOTSPOT(J)  = SQRT( AZEROMOMENTHOTSPOT(J) /  ASECONDMOMENTHOTSPOT(J)  )
          
          
          if ( INDEX .EQ.19) THEN
              
              CHANZXX=3
          
          ENDIF
          
          CHANZXX=3
          
          !NNODEX(INDEX)
          
!       WRITE(932,201) J,NODESPEC(J),NLOOPX(J),AZEROMOMENTSADDLE(J),AZEROMOMENTCROWN(J),TTZSADDLE(J)
!     1           ,AZEROMOMENTSADDLE(J),AZEROMOMENTCROWN(J),TTZCROWN(J) 


!201    FORMAT(I5,2X,I5,2X,I5,2X,E12.5,2X,E12.5,2X,F10.3,2X,E12.5,2X,E12.5,2X,F10.3)
          
      WRITE(932,201) J,NODESPEC(J),NLOOPX(J),AZEROMOMENTHOTSPOT(J),ASECONDMOMENTHOTSPOT(J),TTZHOTSPOT(J)
!     1           ,AZEROMOMENTSADDLE(J),AZEROMOMENTCROWN(J),TTZCROWN(J) 


201    FORMAT(I5,2X,I5,2X,I5,2X,E12.5,2X,E12.5,2X,F10.3,2X,E12.5,2X,E12.5,2X,F10.3)

   
       
       WRITE(982,9201) J,',',NODESPEC(J),',',NLOOPX(J),',',AZEROMOMENTSADDLE(J),',',AZEROMOMENTCROWN(J),',',TTZSADDLE(J)
     1           ,',',AZEROMOMENTSADDLE(J),',',AZEROMOMENTCROWN(J),',',TTZCROWN(J) 


9201    FORMAT(I5,A,I5,A,I5,A,E12.5,A,E12.5,A,F10.3,A,E12.5,A,E12.5,A,F10.3)
          
       ENDDO
       
          
       
       !================================================================================================================
       ! NEW DAMAGE
       ! COMMON /S_N_CURVE_JOINT/ AMATERIAL_JOINT, BMMATERIAL_JOINT,STRESSEDURANCE_JOINT,CPAMETER_JOINT,RPARAMETER_JOINT       
       !================================================================================================================
       
       IDATADAMAGE = 1
       DO K = 1,NWAVESCAT
              DO I = 1,IDATA
                  
                  !CALL SAFETY_FACTOR_FATIGUE_DESIGN_SELECTION(10,SF,DESIGNLIFEX,CONDITION,NPLANE)
                                  
                  !STRESSCALCULATION = AZEROMOMENTSADDLE(IDATADAMAGE)
                  
                  PERIODi   = PERIODSCAT(NLOOPX(IDATADAMAGE))
                  
                  OnedaySecond = 60d0*60d0*24d0
                  
                  ANuse = (OnedaySecond /PERIODi)*365d0/7555.0d0/26.1d0
                  
                  AMAGNITUD = AMENITUDESCAT(NLOOPX(IDATADAMAGE))
                  
                  OccurentNum = AMAGNITUD*60d0*60d0*24d0*365.5D0*10**7D0

                  
!                  IF ( ABS(AZEROMOMENTSADDLE(IDATADAMAGE)) .GT. STRESSEDURANCE_JOINT) THEN
!                  
!                      AMATERIAL_CAL =  AMATERIAL_JOINT
!                      POWER_M       =  BMMATERIAL_JOINT
!                      GINPUT        =  (2D0+POWER_M)/2D0
!                      CALL GAMMA_FUNCTION( GINPUT ,GAMMAOUT)
!                                            
!                  ELSE
!                  
!                      AMATERIAL_CAL =  CPAMETER_JOINT
!                      POWER_M       =  RPARAMETER_JOINT  
!                      CALL GAMMA_FUNCTION( POWER_M ,GAMMAVALUE)
!                      GINPUT        =  (2D0+POWER_M)/2D0
!                      CALL GAMMA_FUNCTION( GINPUT ,GAMMAOUT)
!                      
!                  ENDIF
!                  
!
!                  
!          SADDLEDAMAGE(IDATADAMAGE) = OccurentNum*((8D0*ABS(AZEROMOMENTSADDLE(IDATADAMAGE)))**(POWER_M /2D0))/AMATERIAL_CAL*GAMMAOUT
!          
!          ANlimitS = AMATERIAL_CAL / ( (  ABS(AZEROMOMENTSADDLE(IDATADAMAGE))   )**(POWER_M) )
!          
!          SADDLEDAMAGE(IDATADAMAGE) = ( ANuse / ANlimitS )
          
!                  IF ( ABS(AZEROMOMENTCROWN(IDATADAMAGE)) .GT. STRESSEDURANCE_JOINT) THEN
!                  
!                      AMATERIAL_CAL =  AMATERIAL_JOINT
!                      POWER_M       =  BMMATERIAL_JOINT
!                      GINPUT        =  (2D0+POWER_M)/2D0
!                      CALL GAMMA_FUNCTION( GINPUT ,GAMMAOUT)
!                      
!                      
!                  ELSE
!                  
!                      AMATERIAL_CAL =  CPAMETER_JOINT
!                      POWER_M       =  RPARAMETER_JOINT  
!                      CALL GAMMA_FUNCTION( POWER_M ,GAMMAVALUE)
!                      GINPUT        =  (2D0+POWER_M)/2D0
!                      CALL GAMMA_FUNCTION( GINPUT ,GAMMAOUT)
!                      
!                  ENDIF
!                  
!          CROWNDAMAGE(IDATADAMAGE) = OccurentNum*((8D0*ABS(AZEROMOMENTCROWN(IDATADAMAGE)))**(POWER_M /2D0))/AMATERIAL_CAL*GAMMAOUT
!          
!          NlimitC = AMATERIAL_CAL*( (  ABS(AZEROMOMENTCROWN(IDATADAMAGE)) )**(-POWER_M) )
!                  
!          CROWNDAMAGE(IDATADAMAGE) = ( ANuse / ANlimitS )
!
!                  !WRITE(*,*)SADDLEDAMAGE(IDATADAMAGE), CROWNDAMAGE(IDATADAMAGE)
          
                  IF ( ABS(AZEROMOMENTHOTSPOT(IDATADAMAGE)) .GT. STRESSEDURANCE_JOINT) THEN
                  
                      AMATERIAL_CAL =  AMATERIAL_JOINT
                      POWER_M       =  BMMATERIAL_JOINT
                      GINPUT        =  (2D0+POWER_M)/2D0
                      CALL GAMMA_FUNCTION( GINPUT ,GAMMAOUT)
                                            
                  ELSE
                  
                      AMATERIAL_CAL =  CPAMETER_JOINT
                      POWER_M       =  RPARAMETER_JOINT  
                      CALL GAMMA_FUNCTION( POWER_M ,GAMMAVALUE)
                      GINPUT        =  (2D0+POWER_M)/2D0
                      CALL GAMMA_FUNCTION( GINPUT ,GAMMAOUT)
                      
                  ENDIF
                  

                  
          !!SADDLEDAMAGE(IDATADAMAGE) = OccurentNum*((8D0*ABS(AZEROMOMENTHOTSPOT(IDATADAMAGE)))**(POWER_M /2D0))/AMATERIAL_CAL*GAMMAOUT
          
          ANlimitS = AMATERIAL_CAL / ( (  ABS(AZEROMOMENTHOTSPOT(IDATADAMAGE))   )**(POWER_M) )
          
          AHOTSPOTDAMAGE(IDATADAMAGE) = ( ANuse / ANlimitS )
                  
                  IDATADAMAGE = IDATADAMAGE +1D0
                  
           ENDDO
       ENDDO
       
       
       
       GOTO 29000
       
       !=============================================================================
       ! EFFECTIVE STRESS 
       !=============================================================================
       ! 
       ! INPUT DATA AMSN
       ! SUBROUTINE GAMMA_FUNCTION(X,GA)
       !EFFSTRESSSADDLE(100000), EFFSTRESSCROWN(100000)
       
       AMSN = 5D0
       
          WRITE(933,204)
204       FORMAT(' NUM    JOINT  NSCAT    EFFSTRESSSADDLE     EFFSTRESSCROWN  ')
          
          WRITE(983,9204) ',' , ',' , ',' , ','
9204      FORMAT(' NUM ',A,'    JOINT ',A,' NSCAT  ',A,'  EFFSTRESSSADDLE  ',A,'   EFFSTRESSCROWN  ')
          
          WRITE(934,206)
      !WRITE(ITO,206)
206       FORMAT(' NUM    JOINT  NSCAT     SADDLE_DAMAGE       CROWN_DAMAGE  ')
       
       DO J = 1, NWAVESCAT * IDATA
           
           CALL  SN_PARAMETER(AZEROMOMENTSADDLE(J),AMSNSADDLE,AA)
           
           CALL  SN_PARAMETER(AZEROMOMENTCROWN(J),AMSNCROWN,AA)
                  
           XINPUTGASADDLE =   (2D0+AMSNSADDLE)/2D0 
           
           XINPUTGACROWN =   (2D0+AMSNCROWN)/2D0 
            
           CALL GAMMA_FUNCTION( XINPUTGASADDLE,GASADDLE)
           
           CALL GAMMA_FUNCTION( XINPUTGACROWN,GACROWN)
           
       EFFSTRESSSADDLE(J) = SQRT(8D0*ABS(AZEROMOMENTSADDLE(J))) * (( GASADDLE )**(1D0/AMSN))   
             
       EFFSTRESSCROWN(J)  = SQRT(8D0*ABS(AZEROMOMENTCROWN(J))) * (( GACROWN )**(1D0/AMSN))   
           
           
       WRITE(933,203) J,NODESPEC(J),NLOOPX(J),EFFSTRESSSADDLE(J),EFFSTRESSCROWN(J)

203    FORMAT(I5,2X,I5,2X,I5,6X,E12.5,8X,E12.5)
       
       WRITE(983,9203) J,',',NODESPEC(J),',',NLOOPX(J),',',EFFSTRESSSADDLE(J),',',EFFSTRESSCROWN(J)

9203   FORMAT(I5,A,I5,A,I5,A,E12.5,A,E12.5)
       
          
      !=============================================================================
      ! CALCULATION DAMAGE 
      
      !CALL DAMAGE_CALCULATION(EFFECTIVE_STRESS,AMENITUDESCAT(N),DAMAGE)
      !AMAGNITUD =  AMENITUDESCAT(N)
      !CALL DAMAGE_CALCULATION(EFFECTIVE_STRESS,MAGNITUD,DAMAGE)
      
      !============================================================================
      !COMMON/WAVE_SCATTER/ NUMSCAT(1000),HSCAT(1000),PERIODSCAT(1000),AMENITUDESCAT(1000)
      !AMENITUDESCAT(1000)
       
       AMAGNITUD = AMENITUDESCAT(NLOOPX(J))
       
       ! SADDLE DAMAGE SADDLEDAMAGE(100000),CROWNDAMAGE(100000)
       CALL DAMAGE_CALCULATION_JOINT(EFFSTRESSSADDLE(J),AMAGNITUD,SADDLEDAMAGE(J))
       
       ! BRACE DAMAGE
       CALL DAMAGE_CALCULATION_JOINT(EFFSTRESSCROWN(J),AMAGNITUD,CROWNDAMAGE(J))
       
       WRITE(934,205) J,NODESPEC(J),NLOOPX(J),SADDLEDAMAGE(J),CROWNDAMAGE(J)
       
       
!       WRITE(ITO,205) J,NODESPEC(J),NLOOPX(J),SADDLEDAMAGE(J),CROWNDAMAGE(J)
!       WRITE(*,205) J,NODESPEC(J),NLOOPX(J),SADDLEDAMAGE(J),CROWNDAMAGE(J)

205    FORMAT(I5,2X,I5,2X,I5,6X,E12.5,8X,E12.5)
       
       
       ENDDO
              
29000  CONTINUE
       
      !===========================================================================
      ! CUMULATIVE DAMAGE 
      !====================
       
       DO J = 1,IDATA
           
           TOTALSADDLEDAMAGE_X1 = 0D0
           TOTALCROWNDAMAGE_X2  = 0D0
           TOTALHOTSPOTDAMAGE_X3  = 0D0
           
           DO I = 1,NWAVESCAT
               
               INDEX = J + (I-1)*IDATA
               
               !SADDLEDAMAGE_X1 = SADDLEDAMAGE(INDEX)
               !CROWNDAMAGE_X2  = CROWNDAMAGE(INDEX)
               AHOTSPOTDAMAGE_X3 = AHOTSPOTDAMAGE(INDEX)
               
               !TOTALSADDLEDAMAGE_X1 = TOTALSADDLEDAMAGE_X1 + SADDLEDAMAGE_X1
               !TOTALCROWNDAMAGE_X2  = TOTALCROWNDAMAGE_X2  + CROWNDAMAGE_X2
               TOTALHOTSPOTDAMAGE_X3 = TOTALHOTSPOTDAMAGE_X3 + AHOTSPOTDAMAGE_X3
               
!               write(*,*)TOTALHOTSPOTDAMAGE_X3
               
           ENDDO
           
            !COMMON /DAMAGEFACTOR/ LOCAL_EXPFACTOR(1000),DAMAGEDESIGNFACTOR(1000)
           IF (KFATL.EQ.1) CALL DAMAGE_FACTOR_AUTO_JOINT(NNODE,ALOCALEXFACTORi,FATIGUEDAMAGEFACTORi)
           
           !ALOCALEXFACTORi = 1
           
           !FATIGUEDAMAGEFACTORi = 1
           
           !chanaxswe = JOINTLOOP
           
           
           chana = 3
            
           !IF (KFATL.EQ.1) TOTALSADDLEDAMAGE(J) = TOTALSADDLEDAMAGE_X1 * ALOCALEXFACTORi * FATIGUEDAMAGEFACTORi
           
           !IF (KFATL.EQ.1) TOTALCROWNDAMAGE(J)  = TOTALCROWNDAMAGE_X2 * ALOCALEXFACTORi * FATIGUEDAMAGEFACTORi
           
           IF (KFATL.EQ.1) TOTALHOTSPOTDAMAGE(J)  = TOTALHOTSPOTDAMAGE_X3 * ALOCALEXFACTORi * FATIGUEDAMAGEFACTORi
           
            
           !IF (KFATL.NE.1) TOTALSADDLEDAMAGE(J) = TOTALSADDLEDAMAGE_X1 
           
           !IF (KFATL.NE.1) TOTALCROWNDAMAGE(J)  = TOTALCROWNDAMAGE_X2 
           
           IF (KFATL.NE.1) TOTALHOTSPOTDAMAGE(J)  = TOTALHOTSPOTDAMAGE_X3
           
           !WRITE(*,*) TOTALSADDLEDAMAGE(J) , TOTALCROWNDAMAGE(J) 
           
       ENDDO
       
       chana = 3
       
       
      !==========================================================================================
      !  WRITE DETIL RESULT DATA
      !==========================
       
      REWIND(940)
      
      READ(940,*)
      
      IF (KFATL.NE.1) WRITE(ITO,*) 
      ! KFATL==1 , It will calculate the fatigue with safety factor
      ! KFATL!=1 , It will calculate the fatigue without safety factor
      

!      WRITE(935,1009)
      IF (KFATL.NE.1) WRITE(ITO ,10099)
      WRITE(2935,10099)
      
1009  FORMAT('JONT_NUMB   FREQ   LOOP CONNECT PLAN  TYPE    MEMBER  SADDL_DAMAGE  CROWN_DAMAGE  SADDLE_FATIGUELIFE 
     1  CROWN_FATIGUELIFE')
      
10099  FORMAT('JONT_NUMB   FREQ   LOOP CONNECT PLAN  TYPE    MEMBER  POSITION      DAMAGE(1 year)       FATIGUELIFE ')      

      WRITE(985,1909)',',',',',',',',',',',',',',',',',',','
      
1909  FORMAT('JONT_NUMB',A,' FREQ ',A,'  LOOP ',A,' CONNECTIVITY ',A,'PLANE',A,' TYPE ',A,' MEMBER ',A,' SADDL_DAMAGE ',A,
     1 ' CROWN_DAMAGE ',A,' SADDLE_FATIGUELIFE ',A,' CROWN_FATIGUELIFE')
      
      INDEX = 1D0
      
      DO J = 1,IDATA
          
      READ(940,1010) NNODE,FREQ,LOOP,NCON1,NCON2,JOINTTYPE,MEMBER, HOPPOSITION , AMAXHOTSOPT
!1010  format(I5,2X,F10.3,2X,I4,2X,I5,2X,I4,3X,A3,5X,A5,2X,E12.5,2X,E12.5,2X,I5)    
      
1010  format(I5,2X,F10.3,2X,I4,2X,I5,2X,I4,3X,A3,5X,A5,2X,A2,2X,E12.5)     
           
      !FATIGUELIFESADDLE = 1D0 / TOTALSADDLEDAMAGE(J)
      !FATIGUELIFEBRACE  = 1D0 / TOTALCROWNDAMAGE(J)
          
!           WRITE(935,1020)NNODE,FREQ,LOOP,NCON1,NCON2,JOINTTYPE,MEMBER,TOTALSADDLEDAMAGE(J),TOTALCROWNDAMAGE(J),
!     1  FATIGUELIFESADDLE,FATIGUELIFEBRACE
1020  format(I5,2X,F10.3,2X,I4,2X,I5,2X,I4,3X,A3,5X,A5,2X,E12.5,2X,E12.5,8X,E12.5,8X,E12.5)   
      
      
!      if (TOTALSADDLEDAMAGE(J).GT.TOTALCROWNDAMAGE(J))then
!          XDAMAGEJOINT = TOTALSADDLEDAMAGE(J)
!          XFATIGUELIFT = 1D0/XDAMAGEJOINT
!          DPOSITION    = 'SADDLE'
!      ELSE 
!          XDAMAGEJOINT = TOTALCROWNDAMAGE(J)
!          XFATIGUELIFT = 1D0/XDAMAGEJOINT
!          DPOSITION    = 'CROWN '
!      ENDIF
      
      XDAMAGEJOINT = TOTALHOTSPOTDAMAGE(J)
      XFATIGUELIFT = 1D0/XDAMAGEJOINT
      DPOSITION = HOPPOSITION
         
      !========================================      
!      KOFFL   = OFFSHORE 
!      KSPEC   = SPECTRAL
!      KDESIGN = STEEL DESIGN
!      KFATM   = FATIGUE MEMBER
!      KFATJ   = FATIGUE JOINT
!      KFATL   = FATIGUE LIFE
!      KFAST   = FAST OPTION
!      KOREV   = RELATIVE FLOW ( MORISON EQ. )
      !========================================
      
      IF (KFATL.NE.1)  WRITE(ITO,10209)NNODE,FREQ,LOOP,NCON1,NCON2,JOINTTYPE,MEMBER,DPOSITION,XDAMAGEJOINT,XFATIGUELIFT
          
      WRITE(2935,10209)NNODE,FREQ,LOOP,NCON1,NCON2,JOINTTYPE,MEMBER,DPOSITION,XDAMAGEJOINT,XFATIGUELIFT
10209  format(I5,2X,F10.3,2X,I4,2X,I5,2X,I4,3X,A3,5X,A5,5X,A6,5X,E12.5,8X,E12.5)      
      
          
!          WRITE(985,8020)NNODE,',',FREQ,',',LOOP,',',NCON1,',',NCON2,',',JOINTTYPE,',',MEMBER,',',
!     1  TOTALSADDLEDAMAGE(J),',',TOTALCROWNDAMAGE(J),',', FATIGUELIFESADDLE,',',FATIGUELIFEBRACE
!          
!8020  format(I5,A,F10.3,A,I4,A,I5,A,I4,A,A3,A,A5,A,E12.5,A,E12.5,A,E12.5,A,E12.5)   
          
          INDEX  = INDEX + 1D0 
          
      ENDDO
      
      
    
      
      !==========================================================================================
      !  WRITE DETIL RESULT DATA
      !=====================
      
!      REWIND(935)
!      
!      READ(935,*)
!      
!       DO J = 1,IDATA
!           
!       READ(935,1020)NNODE,FREQ,LOOP,NCON1,NCON2,JOINTTYPE,MEMBER,TOTALSADDLEDAMAGE(J),TOTALCROWNDAMAGE(J),
!     1  FATIGUELIFESADDLE,FATIGUELIFEBRACE    
!           
!       IF ( TOTALSADDLEDAMAGE(J) .GT. TOTALCROWNDAMAGE(J) ) THEN
!           AMAXDAMAGEJOINT = TOTALSADDLEDAMAGE(J)
!           FATIGUELIFEJOINT = FATIGUELIFESADDLE
!       ELSE
!           AMAXDAMAGEJOINT = TOTALCROWNDAMAGE(J)
!           FATIGUELIFEJOINT =FATIGUELIFEBRACE
!       ENDIF 
!           
!       ENDDO
!       
!       WRITE(ITO,2020)NNODE,JOINTTYPE,MEMBER,AMAXDAMAGEJOINT,FATIGUELIFEJOINT       
!2020         format(I5,2X,A3,5X,A5,2X,E12.5,2X,E12.5,8X)        
!      
      
      !========================================      
!      KOFFL   = OFFSHORE 
!      KSPEC   = SPECTRAL
!      KDESIGN = STEEL DESIGN
!      KFATM   = FATIGUE MEMBER
!      KFATJ   = FATIGUE JOINT
!      KFATL   = FATIGUE LIFE
!      KFAST   = FAST OPTION
!      KOREV   = RELATIVE FLOW ( MORISON EQ. )
      !========================================
      
      IF (KFATL.EQ.1) CALL JOINT_FATIGUE_DESIGN(IDATA)
      IF (KFATL.EQ.0) CLOSE(UNIT=936,status='DELETE')
      
      IF (KFATL.EQ.0) CLOSE(UNIT=935,status='DELETE')
      
      RETURN
      END
!=====================================================================================================================================      
!=====================================================================================================================================      
      SUBROUTINE JOINT_FATIGUE_DESIGN(IDATA)
      
      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT INTEGER*4 (i-n)
      CHARACTER*5 JOINTTYPE , MEMBER
      CHARACTER*2 STATUSSADDLE , STATUSCROWN
      CHARACTER*4 CONDITION
      
      COMMON /INPUTJOINT/ NNODEJOINT(1000),JOINTCASE(1000),SAFTYFACTOR(1000),DESIGNLIFE(1000),GAP_JOINT(1000),JOINTLOOP
      
!      COMMON /MOMENTSPECTYRUM/ AZEROMOMENTSADDLE(200000), AZEROMOMENTCROWN(200000),
!     1                         ASECONDMOMENTSADDLE(200000), ASECONDMOMENTCROWN(200000),
!     1                         TTZSADDLE(200000) , TTZCROWN(200000)  ,NODESPEC(200000),NLOOPX(200000),
!     1            EFFSTRESSSADDLE(200000), EFFSTRESSCROWN(200000),
!     1            SADDLEDAMAGE(200000),CROWNDAMAGE(200000),
!     1            TOTALSADDLEDAMAGE(200000),TOTALCROWNDAMAGE(200000)
      
      COMMON /MOMENTSPECTYRUM/ AZEROMOMENTSADDLE(200000), AZEROMOMENTCROWN(200000),AZEROMOMENTHOTSPOT(200000)
     1                        , ASECONDMOMENTSADDLE(200000), ASECONDMOMENTCROWN(200000),ASECONDMOMENTHOTSPOT(200000)
     1                        , TTZHOTSPOT(200000) , TTZSADDLE(200000) , TTZCROWN(200000)  ,NODESPEC(200000),NLOOPX(200000),
     1            EFFSTRESSSADDLE(200000), EFFSTRESSCROWN(200000),
     1            SADDLEDAMAGE(200000),CROWNDAMAGE(200000),AHOTSPOTDAMAGE(200000),
     1            TOTALSADDLEDAMAGE(200000),TOTALCROWNDAMAGE(200000),TOTALHOTSPOTDAMAGE(200000)
      
      COMMON /INOU/ ITI,ITO,ISO,NDATI,NPLOT,NKFAC,NELEM,IFPR(10),IFPL(10)
      COMMON /LINEAT/ KTRAF,KEATH,KCSAL,KOFFL,KSPEC,KDESIGN,KFATM,KFATJ,KFATL,KFAST,KOREV
      
      ALLOCATABLE NNODE(:)
      
      ALLOCATE(NNODE(IDATA))
      
      REWIND(940)
      
      READ(940,*)
      
      !=======================================================================
      ! KFATL==1 , It will calculate the fatigue with safety factor
      ! KFATL!=1 , It will calculate the fatigue without safety factor
      IF (KFATL.EQ.1)  WRITE(ITO,*)
      IF (KFATL.EQ.1)  WRITE(ITO,1009)
      !=======================================================================
      
      WRITE(936,1009)
      
1009  FORMAT('JONT_NUMB   FREQ   LOOP CONNECT PLAN  TYPE    MEMBER    SAFETY_FACTOR  LOCATION  DESIGN_LIFE        DAMAGE    
     1 FATIGUE_LIFE  STATUS')
      
!old1009  FORMAT('JONT_NUMB   FREQ   LOOP CONNECT PLAN  TYPE    MEMBER    SAFETY_FACTOR   DESIGN LIFE    SADDL_DAMAGE  CROWN_DAMAGE     
!     1  SADDLE_FATIGUELIFE  STATUS CROWN_FATIGUELIFE  STATUS')
      
      WRITE(986,1809)',',',',',',',',',',',',',',',',',',',',',',',',',',','
      
1809  FORMAT('JONT_NUMB',A,' FREQ ',A,'  LOOP ',A,' CONNECT ',A,' PLAN ',A,'  TYPE  ',A,'  MEMBER ',A,'   SAFETY_FACTOR ',A,'  
     1  DESIGN LIFE  ',A,'  SADDL_DAMAGE ',A,' CROWN_DAMAGE
     1  ',A,' SADDLE_FATIGUELIFE ',A,'  STATUS ',A,' CROWN_FATIGUELIFE  ',A,' STATUS')
            

      DO J = 1,IDATA
          
      READ(940,1010) NNODE(J),FREQ,LOOP,NCON1,NCON2,JOINTTYPE,MEMBER, HOPPOSITION , AMAXHOTSOPT
!1010  format(I5,2X,F10.3,2X,I4,2X,I5,2X,I4,3X,A3,5X,A5,2X,E12.5,2X,E12.5,2X,I5)    
      
     
 
      
1010  format(I5,2X,F10.3,2X,I4,2X,I5,2X,I4,3X,A3,5X,A5,2X,A2,2X,E12.5)     
      
      CALL SCF_JOINT_CONDITION(NNODE(J),CONDITION)
      
      CALL JOINT_MEMBER_PLANE(NPLANE,NCHORD,NBRACE,J)
           
      CALL SAFETY_FACTOR_FATIGUE_DESIGN_SELECTION(NNODE(J),SF,DESIGNLIFEX,CONDITION,NPLANE)
      

      !ASADDLEDAMAGE = TOTALSADDLEDAMAGE(J) * SF 
      ! ACROWNDAMAGE  = TOTALCROWNDAMAGE(J)  * SF 
      
      AHOTSPORTDAMAGE = TOTALHOTSPOTDAMAGE(J)  * SF 
      
      !FALSADDLE  = 1D0 / ASADDLEDAMAGE
      !FALCROWN   = 1D0 / ACROWNDAMAGE
      FALHOTSPOT   = 1D0 / AHOTSPORTDAMAGE
      
!      IF(FALSADDLE .GT. DESIGNLIFEX ) THEN
!      STATUSSADDLE = 'OK'
!      ELSE
!      STATUSSADDLE = 'NO'    
!      ENDIF
!      
!      IF(FALCROWN .GT. DESIGNLIFEX ) THEN
!      STATUSCROWN = 'OK'
!      ELSE
!      STATUSCROWN = 'NO'    
!      ENDIF
      
      IF(FALHOTSPOT .GT. DESIGNLIFEX ) THEN
      STATUSCROWN = 'OK'
      ELSE
      STATUSCROWN = 'NO'    
      ENDIF
      
!old      WRITE(936,1020)NNODE(J),FREQ,LOOP,NCON1,NCON2,JOINTTYPE,MEMBER,SF,DESIGNLIFEX,ASADDLEDAMAGE,ACROWNDAMAGE,
!old     1  FALSADDLE,STATUSSADDLE,FALCROWN,STATUSCROWN
      
      
!1020  format(I5,2X,F10.3,2X,I4,2X,I5,2X,I4,3X,A3,5X,A5,5X,F10.3,5X,F10.2,5X,E12.5,2X,E12.5,2X,F17.5,8X,A2,2X,F17.5,6X,A2) 
      
      
!      if (ASADDLEDAMAGE.GT.ACROWNDAMAGE) then
!          DAMAGEII = ASADDLEDAMAGE
!          FatigueLifei =  1D0 / ( DAMAGEII * SF)
!      else
!          DAMAGEII = ACROWNDAMAGE
!          FatigueLifei =  1D0 / ( DAMAGEII * SF)
!      endif
      
          DAMAGEII = AHOTSPORTDAMAGE
          FatigueLifei =  1D0 / ( DAMAGEII * SF)
      
      IF(FatigueLifei .GT. DESIGNLIFEX ) THEN
      STATUSFatigue = 'OK'
      ELSE
      STATUSFatigue = 'NO'    
      ENDIF
      
      DAMAGEII = DAMAGEII * DESIGNLIFEX
      

       WRITE(936,1021)NNODE(J),FREQ,LOOP,NCON1,NCON2,JOINTTYPE,MEMBER,SF,HOPPOSITION,DESIGNLIFEX,DAMAGEII,FatigueLifei,
     1   STATUSCROWN
       
       
!     1  FALSADDLE,STATUSSADDLE,FALCROWN,STATUSCROWN
!      
1021  format(I5,2X,F10.3,2X,I4,2X,I5,2X,I4,3X,A3,5X,A5,5X,F10.3,7X,A2,5X,F10.2,5X,E12.5,3X,E12.5,5X,A2)       
      
      IF (KFATL.EQ.1) THEN 
      WRITE(ITO,1021)NNODE(J),FREQ,LOOP,NCON1,NCON2,JOINTTYPE,MEMBER,SF,DESIGNLIFEX,DAMAGEII,FatigueLifei,
     1   STATUSFatigue
      Endif
      
      
      WRITE(986,1820)NNODE(J),',',FREQ,',',LOOP,',',NCON1,',',NCON2,',',JOINTTYPE,',',MEMBER,',',SF,',',
     1  DESIGNLIFEX,',',ASADDLEDAMAGE,',',ACROWNDAMAGE,',',FALSADDLE,',',STATUSSADDLE,',',FALCROWN,',',STATUSCROWN
      
1820  format(I5,A,F10.3,A,I4,A,I5,A,I4,A,A3,A,A5,A,F10.3,A,F10.2,A,E12.5,A,E12.5,A,F17.5,A,A2,A,F17.5,A,A2)   
          
      ENDDO
      
      DEALLOCATE(NNODE)
      
      RETURN
      END SUBROUTINE
!=====================================================================================================================================   
!=====================================================================================================================================   
      SUBROUTINE DAMAGE_FACTOR_AUTO_JOINT(NNODE,ALOCALEXFACTORi,FATIGUEDAMAGEFACTORi)
      
      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT INTEGER*4 (i-n)
      
      !COMMON /INPUTJOINT/ NNODEJOINT(1000),JOINTCASE(1000),SAFTYFACTOR(1000),DESIGNLIFE(1000),JOINTLOOP
      COMMON /INPUTJOINT/ NNODEJOINT(1000),JOINTCASE(1000),SAFTYFACTOR(1000),DESIGNLIFE(1000),GAP_JOINT(1000),JOINTLOOP
      COMMON /DAMAGEFACTOR/ ALOCAL_EXPFACTOR(1000),DAMAGEDESIGNFACTOR(1000)
      
      
      DO I=1,JOINTLOOP
      IF ( NNODE .EQ. NNODEJOINT(I)) THEN
          ALOCALEXFACTORi =  ALOCAL_EXPFACTOR(I)
          FATIGUEDAMAGEFACTORi = DAMAGEDESIGNFACTOR(I)
          GOTO 100
      ENDIF
      ENDDO
100   CONTINUE

      RETURN
      END SUBROUTINE
!=====================================================================================================================================         
!=====================================================================================================================================
      SUBROUTINE DAMAGE_CALCULATION_JOINT(EFFECTIVE_STRESS,AMENITUDESCAT,DAMAGE)
      
      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT INTEGER*4 (i-n)
      
      COMMON /S_N_CURVE_JOINT/ AMATERIAL_JOINT, BMMATERIAL_JOINT,STRESSEDURANCE_JOINT,CPAMETER_JOINT,RPARAMETER_JOINT
      
      ! DUMMY INPUT
      
      AMATERIAL      = AMATERIAL_JOINT
      BMMATERIAL     = BMMATERIAL_JOINT
      STRESSEDURANCE = STRESSEDURANCE_JOINT
      CPAMETER       = CPAMETER_JOINT
      RPARAMETER     = RPARAMETER_JOINT
      
      
      ! USING DATA FORM S-N CURVE
      
      IF(ABS(EFFECTIVE_STRESS).LE.STRESSEDURANCE)THEN
          
      DAMAGE =  AMENITUDESCAT*(EFFECTIVE_STRESS**RPARAMETER)/CPAMETER 
      ELSE
      DAMAGE =  AMENITUDESCAT*(EFFECTIVE_STRESS**BMMATERIAL)/AMATERIAL
      ENDIF
      
      RETURN
      END !SUBROUTINE
!=====================================================================================================================================      
!=====================================================================================================================================
      SUBROUTINE SN_PARAMETER(EFFECTIVE_STRESS,AMSN,AASN)
      
      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT INTEGER*4 (i-n)
      
      COMMON /S_N_CURVE_JOINT/ AMATERIAL_JOINT, BMMATERIAL_JOINT,STRESSEDURANCE_JOINT,CPAMETER_JOINT,RPARAMETER_JOINT

  
      ! USING DATA FORM S-N CURVE
      
      IF(ABS(EFFECTIVE_STRESS).LE.STRESSEDURANCE)THEN
            
      AASN = CPAMETER_JOINT
      AMSN = RPARAMETER_JOINT
      
      ELSE
       
      AASN = AMATERIAL_JOINT
      AMSN = BMMATERIAL_JOINT

      ENDIF
      
!      CLOSE(UNIT=930,status='DELETE')
!      CLOSE(UNIT=934,status='DELETE')
      
      RETURN
      END !SUBROUTINE
!=====================================================================================================================================      
!=====================================================================================================================================      
!=====================================================================================================================================      
!=====================================================================================================================================
      SUBROUTINE SAFETY_FACTOR_FATIGUE_DESIGN_SELECTION(NJOINT,SF,DESIGNLIFEXX,CONDITION,NPLANE)
      
      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT INTEGER*4 (i-n)
      CHARACTER*4 CONDITION
      
      !COMMON /INPUTJOINT/ NNODEJOINT(1000),JOINTCASE(1000),SAFTYFACTOR(1000),DESIGNLIFE(1000),JOINTLOOP
      COMMON /INPUTJOINT/ NNODEJOINT(1000),JOINTCASE(1000),SAFTYFACTOR(1000),DESIGNLIFE(1000),GAP_JOINT(1000),JOINTLOOP
      COMMON / SCFMANUAL /  SCFCHORDSADDLEMANL(2,1000,2),  SCFCHORDCROWNMANL(2,1000,2)
     1                     ,SCFBRACESADDLEMANL_A(1000,2,3),SCFBRACECROWNMANL_A(1000,2,3),SFMANUAL(1000,2),LIFEMANUAL(1000,2)  
      
      COMMON /JOINTMANUAL/ NNODEJOINTM(1000),NNPLANE(1000),SCFCHORDCROWN(1000),SCFCHORDSADDLE(1000),SCFACROWN(1000),SCFBCROWN(1000)
     1                    ,SCFCCROWN(1000),SCFASADDLE(1000),SCFBCSADDLE(1000),SCFCSADDLE(1000),JOINTLOOPMANUAL
      
      IF (CONDITION.EQ.'AUTO') THEN
            
      DO I=1,JOINTLOOP
      IF (NJOINT.EQ.NNODEJOINT(I))THEN
           SF = SAFTYFACTOR(I)
           DESIGNLIFEXX = DESIGNLIFE(I)
      ENDIF
      ENDDO
      
      ELSE
              SF = SFMANUAL(NJOINT,NPLANE) 
              DESIGNLIFEXX = LIFEMANUAL(NJOINT,NPLANE)
      ENDIF
      
      RETURN
      END
!=====================================================================================================================================      
!=====================================================================================================================================
      SUBROUTINE JOINT_MEMBER_PLANE(NPLANE,NCHORD,NBRACE,J)
      
      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT INTEGER*4 (i-n)
      COMMON /SAFTYMANUALXX/ NUMBERCHORD(10000),NUMBERBRACE(10000),NUMBERNPLANE(10000)
          NPLANE  = NUMBERNPLANE(J)
          NCHORD  = NUMBERCHORD(J)
          NBRACE  = NUMBERBRACE(J)
          RETURN
      END
      
!=====================================================================================================================================      
!=====================================================================================================================================

      SUBROUTINE SN_curve_Standard(A,BM,SQ,C,R,Ntype)
      
      !AMATERIAL_JOINT,BMMATERIAL_JOINT,STRESSEDURANCE_JOINT,CPAMETER_JOINT,RPARAMETER_JOINT
      
      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT INTEGER*4 (i-n)
      CHARACTER*10 SNTYPE
      CHARACTER*30 SN_NAME
      
      SN_NAME = 'User_Define' ! For Initiation 
      
      IF( Ntype .EQ. 1) THEN
          ! API IN AIR
          SN_NAME = 'API_AIR'
          BM= 3d0
          R = 5.0
          SQ= 6.7*10**7
          
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'AIR')
          xxxx=1
          
          ELSEIF( Ntype .EQ. 2) THEN
          ! API IN SEA WATER (SPECIAL FOR API)
          SN_NAME = 'API_WATER'    
          A = (1.8d0*10**6)/((94.0*10**6)**(-3D0))
          BM= 3d0
          SQ= 9.4*10**7
          C = (1.8d0*10**6)/((94.0*10**6)**(-5D0))
          R = 5.0
          ELSEIF( Ntype .EQ. 3) THEN
          ! B1 in Air
          SN_NAME = 'DNV_B1_AIR'         
          BM= 4d0
          R = 5.0
          SQ= (106.9*10**6)          
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'AIR')

          ELSEIF( Ntype .EQ. 4) THEN
          ! B1 in SEA WATER
          SN_NAME = 'DNV_B1_WATER' 
          BM= 4d0
          R = 5.0
          S7= 106.9*10**6
          
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'WTR')
                    
!          C = (10**7)/((S7)**(-R))  
!          S6= (C/10**6)**(1/R)
!          SQ= S6
!          A = (10**6)/((S6)**(-BM))
          xxxx=1
          ELSEIF( Ntype .EQ. 5) THEN
          !B2 in Air
          SN_NAME = 'DNV_B2_AIR'  
          BM= 4d0
          R = 5.0
          SQ= (93.59*10**6)
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'AIR')
          xxxx=1
          ELSEIF( Ntype .EQ. 6) THEN
          !B2 in SEA WATER
          SN_NAME = 'DNV_B2_WATER'
          BM= 4d0
          R = 5.0
          S7= 93.59*10**6
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'WTR')
          ELSEIF( Ntype .EQ. 7) THEN
          !C in AIR
          SN_NAME = 'DNV_C_AIR'  
          R = 5D0
          BM= 3d0
          SQ= 73.1*10**6
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'AIR')
          ELSEIF( Ntype .EQ. 8) THEN
          !C in WATER
          SN_NAME = 'DNV_C_WATER' 
          R = 5D0
          BM= 3d0
          S7= 73.1*10**6
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'WTR')
          ELSEIF( Ntype .EQ. 9) THEN
          !C1 in AIR
          SN_NAME = 'DNV_C1_AIR'  
          R = 5D0
          BM= 3d0
          SQ= 65.5*10**6
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'AIR')
          ELSEIF( Ntype .EQ. 10) THEN
          !C1 in WATER
          SN_NAME = 'DNV_C1_WATER'  
          R = 5D0
          BM= 3d0
          S7= 65.5*10**6
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'WTR')
          ELSEIF( Ntype .EQ. 11) THEN
          !C2 in AIR
          SN_NAME = 'DNV_C2_AIR'  
          R = 5D0
          BM= 3d0
          SQ= 5.848*10**7
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'AIR')
          ELSEIF( Ntype .EQ. 12) THEN
          !C2 in WATER
          SN_NAME = 'DNV_C2_WATER' 
          R = 5D0
          BM= 3d0
          S7= 5.848*10**7
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'WTR')
          ELSEIF( Ntype .EQ. 13) THEN
          !D in AIR
          SN_NAME = 'DNV_D_AIR'  
          R = 5D0
          BM= 3d0
          SQ= 52.63*10**6
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'AIR')
          ELSEIF( Ntype .EQ. 14) THEN
          !D in WATER
          SN_NAME = 'DNV_D_WATER'
          R = 5D0
          BM= 3d0
          S7= 52.63*10**6
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'WTR')
          ELSEIF( Ntype .EQ. 15) THEN
          !E in AIR
          SN_NAME = 'DNV_E_AIR'  
          R = 5D0
          BM= 3d0
          SQ= 46.78*10**6
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'AIR')
          ELSEIF( Ntype .EQ. 16) THEN
          !E in WATER
          SN_NAME = 'DNV_E_WATER' 
          R = 5D0
          BM= 3d0
          S7= 46.78*10**6
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'WTR')
          ELSEIF( Ntype .EQ. 17) THEN
          !F in AIR
          SN_NAME = 'DNV_F_AIR'  
          R = 5D0
          BM= 3d0
          SQ= 41.52*10**6
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'AIR')
          ELSEIF( Ntype .EQ. 18) THEN
          !F in WATER
          SN_NAME = 'DNV_F_WATER'
          R = 5D0
          BM= 3d0
          S7= 41.52*10**6
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'WTR')
          ELSEIF( Ntype .EQ. 19) THEN
          !F1 in AIR
          SN_NAME = 'DNV_F1_AIR'  
          R = 5D0
          BM= 3d0
          SQ= 36.84*10**6
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'AIR')
          ELSEIF( Ntype .EQ. 20) THEN
          !F1 in WATER
          SN_NAME = 'DNV_F1_WATER' 
          R = 5D0
          BM= 3d0
          S7= 36.84*10**6
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'WTR')
          ELSEIF( Ntype .EQ. 21) THEN
          !F3 in AIR
          SN_NAME = 'DNV_F3_AIR'  
          R = 5D0
          BM= 3d0
          SQ= 32.75*10**6
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'AIR')
          ELSEIF( Ntype .EQ. 22) THEN
          !F3 in WATER
          SN_NAME = 'DNV_F3_WATER'  
          R = 5D0
          BM= 3d0
          S7= 32.75*10**6
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'WTR')
          ELSEIF( Ntype .EQ. 23) THEN
          !G in AIR
          SN_NAME = 'DNV_G_AIR'
          R = 5D0
          BM= 3d0
          SQ= 29.24*10**6
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'AIR')
          ELSEIF( Ntype .EQ. 24) THEN
          !G in WATER
          SN_NAME = 'DNV_G_WATER'
          R = 5D0
          BM= 3d0
          S7= 29.24*10**6
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'WTR')
          ELSEIF( Ntype .EQ. 25) THEN
          !W1 in AIR
          SN_NAME = 'DNV_W1_AIR'
          R = 5D0
          BM= 3d0
          SQ= 26.32*10**6
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'AIR')
          ELSEIF( Ntype .EQ. 26) THEN
          !W1 in WATER
          SN_NAME = 'DNV_W1_WATER'
          R = 5D0
          BM= 3d0
          S7= 26.32*10**6
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'WTR')         
          ELSEIF( Ntype .EQ. 27) THEN
          !W2 in AIR
          SN_NAME = 'DNV_W2_AIR'
          R = 5D0
          BM= 3d0
          SQ= 23.39*10**6
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'AIR')
          ELSEIF( Ntype .EQ. 28) THEN
          !W2 in WATER
          SN_NAME = 'DNV_W2_WATER'
          R = 5D0
          BM= 3d0
          S7= 23.39*10**6
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'WTR')    
          ELSEIF( Ntype .EQ. 29) THEN
          !W3 in AIR
          SN_NAME = 'DNV_W3_AIR'
          R = 5D0
          BM= 3d0
          SQ= 21.05*10**6
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'AIR')
          ELSEIF( Ntype .EQ. 30) THEN
          !W3 in WATER
          SN_NAME = 'DNV_W3_WATER'
          R = 5D0
          BM= 3d0
          S7= 21.05*10**6
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'WTR')     
          ELSEIF( Ntype .EQ. 31) THEN
          !T in AIR
          SN_NAME = 'DNV_T_AIR'
          R = 5D0
          BM= 3d0
          SQ= 52.63*10**6
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'AIR')
          ELSEIF( Ntype .EQ. 32) THEN
          !T in WATER
          SN_NAME = 'DNV_T_WATER'
          R = 5D0
          BM= 3d0
          S7= 52.63*10**6
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'WTR')    
          ELSEIF( Ntype .EQ. 100) THEN
          !ISO in AIR
          SN_NAME = 'ISO_AIR'
          R = 5D0
          BM= 3d0
          SQ= 67.091371*10**6
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'AIR')
          ELSEIF( Ntype .EQ. 102) THEN
          !T in WATER
          SN_NAME = 'ISO_WATER'
          R = 5D0
          BM= 3d0
          S7= 66.98846094*10**6
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'WTR')    
          ELSEIF( Ntype .EQ. 103) THEN
          !ISO in AIR
          SN_NAME = 'Korea_Standard_AIR'
          R = 5D0
          BM= 3d0
          SQ= 67.091371*10**6
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'AIR')
          ELSEIF( Ntype .EQ. 104) THEN
          !T in WATER
          SN_NAME = 'Korea_Standard_WATER'
          R = 5D0
          BM= 3d0
          S7= 66.98846094*10**6
          CALL SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,'WTR')    
          
          ENDIF
      
          
          Call Plot_SN(BM,R,SQ,S7,C,A,'WTR',SN_NAME) 
          
          
      RETURN
      END SUBROUTINE
!=====================================================================================================================================      
!=====================================================================================================================================
	SUBROUTINE Plot_SN(BM,R,SQ,S7,C,A,TYPES,SN_NAME)  !ELEMENT DATA
	IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT INTEGER*4 (I-N)
             
      Dimension AXNUMBER(100),AYSTRESS(100)
      
      CHARACTER*30 SN_NAME
      CHARACTER*10 SNTYPE
      CHARACTER*3  TYPES
      
      AXNUMBER(1) = 1*10**4 
      AXNUMBER(2) = 2*10**4
      AXNUMBER(3) = 3*10**4
      AXNUMBER(4) = 4*10**4
      AXNUMBER(5) = 5*10**4
      AXNUMBER(6) = 6*10**4
      AXNUMBER(7) = 7*10**4
      AXNUMBER(8) = 8*10**4
      AXNUMBER(9) = 9*10**4
      AXNUMBER(10) = 1*10**5
      AXNUMBER(11) = 2*10**5
      AXNUMBER(12) = 3*10**5
      AXNUMBER(13) = 4*10**5
      AXNUMBER(14) = 5*10**5
      AXNUMBER(15) = 6*10**5
      AXNUMBER(16) = 7*10**5
      AXNUMBER(17) = 8*10**5
      AXNUMBER(18) = 9*10**5
      AXNUMBER(19) = 1*10**6
      AXNUMBER(20) = 2*10**6
      AXNUMBER(21) = 3*10**6
      AXNUMBER(22) = 4*10**6
      AXNUMBER(23) = 5*10**6
      AXNUMBER(24) = 6*10**6
      AXNUMBER(25) = 7*10**6
      AXNUMBER(26) = 8*10**6
      AXNUMBER(27) = 9*10**6
      AXNUMBER(28) = 1*10**7
      AXNUMBER(29) = 2*10**7
      AXNUMBER(30) = 3*10**7
      AXNUMBER(31) = 4*10**7
      AXNUMBER(32) = 5*10**7
      AXNUMBER(33) = 6*10**7
      AXNUMBER(34) = 7*10**7
      AXNUMBER(35) = 8*10**7
      AXNUMBER(36) = 9*10**7
      AXNUMBER(37) = 1*10**8
      AXNUMBER(38) = 2*10**8
      AXNUMBER(39) = 3*10**8
      AXNUMBER(40) = 4*10**8
      AXNUMBER(41) = 5*10**8
      AXNUMBER(42) = 6*10**8
      AXNUMBER(43) = 7*10**8
      AXNUMBER(44) = 8*10**8
      AXNUMBER(45) = 9*10**8
      AXNUMBER(46) = 1*10**9

      write(5003,*)
      !write(938,*)'SN curve Plot'
      write(5003,20)SN_NAME
20    format(1x,'SN curve Plot',2x,A30)  
      write(5003,*)'====================================='
      write(5003,29)SN_NAME
29    format(1x,'SN Parameters of ',A30)       
      write(5003,*)'====================================='
      write(5003,21) A
21    format(1x,'A =',E10.4)    
      write(5003,22) Bm
22    format(1x,'m =',E10.4)  
      SQX = SQ/(10**6)
      write(5003,23) SQX
23    format(1x,'SQ =',E10.4,2x,'MPa')  
      write(5003,24) C
24    format(1x,'C =',E10.4)    
      write(5003,25) R
25    format(1x,'R =',E10.4)   
      write(5003,*)'====================================='
      
      write(5003,*)'Number_of_Cycle     Stress_Range'
      
      Do i=1,46
          
          AYSTRESS(i) = ( A / AXNUMBER(i) )**(1/BM)
          
      if( AYSTRESS(i).LT. SQ ) then
          
          AYSTRESS(i) = ( C / AXNUMBER(i) )**(1/R)
          
          chana = AXNUMBER(i)
          
      Endif

          write(5003,1) AXNUMBER(i) , AYSTRESS(i) 
1         format(3X,E10.4,6X,E10.4) 
          
      ENDDO
      
      
      
      ! STOP
      
      
      
      End Subroutine
C=====================================================================================================================================
!=====================================================================================================================================      
!=====================================================================================================================================      
!=====================================================================================================================================
      SUBROUTINE SN_CURVE_PARAMETER(BM,R,SQ,S7,C,A,CONDITION)
      
      !AMATERIAL_JOINT,BMMATERIAL_JOINT,STRESSEDURANCE_JOINT,CPAMETER_JOINT,RPARAMETER_JOINT
      
      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT INTEGER*4 (i-n)
      
      CHARACTER*3 CONDITION
      
      IF(CONDITION.EQ.'AIR') THEN
          
          C = (10**7)/((SQ)**(-R))  
          A = (10**7)/((SQ)**(-BM))
          
      ELSEIF(CONDITION.EQ.'WTR') THEN
          
          C = (10**7)/((S7)**(-R))  
          S6= (C/10**6)**(1/R)
          SQ= S6 ! S6 is 1 million cycle
          A = (10**6)/((S6)**(-BM))
          
      ENDIF
           
      END SUBROUTINE
!=====================================================================================================================================      
!=====================================================================================================================================
!=====================================================================================================================================

	SUBROUTINE PRNVALVECHANA(IGM,EDATA,NOUT,LENGTH,MAPP,NV,METHOD,LFPRIN)  !ELEMENT DATA
	IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT INTEGER*4 (I-N)
	CHARACTER*3 METHOD
	CHARACTER*3 BLANK
	
C     FILE INDEX FOR WRITING OUTPUT      
      COMMON /XFPOUT/ KEXCEL,LFPRN1,LFPRN2,LFPRN3,LFPRN4	
	
C     ----------------------------------------------------------------
	DIMENSION EDATA(1),PDATA(20),MAPP(1)
C     ----------------------------------------------------------------
      KEXCEL=0D0
	NUM = NOUT/LENGTH

	DO IPT = 1,NUM

	DO J = 1,NV
	PDATA(J) = 0.0D0
	M = MAPP(J)

	IF(M.NE.0) THEN
	SELECTCASE(METHOD)
	CASE('MAX')
	PDATA(J) = EDATA(M+LENGTH*(IPT-1))
	CASE('MIN')
	PDATA(J) = EDATA(M+LENGTH*(IPT-1)+NOUT)
	ENDSELECT
	IF(ABS(PDATA(J)).LT.1.0E-12) PDATA(J) = 0.0D0
	ENDIF

	ENDDO


      IF(IPT.EQ.1) THEN
	  
	  IF(KEXCEL.EQ.0) WRITE(LFPRIN,100) IGM,(PDATA(J),J=1,NV)
	  !KEXCEL=0D0
        IF(KEXCEL.EQ.1) THEN
         WRITE(LFPRIN,110) IGM,','
         DO J = 1,NV
         IF(J.LT.NV)  WRITE(LFPRIN,120) PDATA(J),','
         IF(J.EQ.NV)  WRITE(LFPRIN,120) PDATA(J)   !EXCEL
	 ENDDO
        ENDIF
        
      ENDIF
         
!      IF(IPT.NE.1) THEN
        
!        IF(KEXCEL.EQ.0) WRITE(LFPRIN,101)  (PDATA(J),J=1,NV)
!        KEXCEL=0D0
!        IF(KEXCEL.EQ.1) THEN
!         WRITE(LFPRIN,111) BLANK,','
!         DO J = 1,NV
!         IF(J.LT.NV)  WRITE(LFPRIN,120) PDATA(J),','
!         IF(J.EQ.NV)  WRITE(LFPRIN,120) PDATA(J)   !EXCEL
!         ENDDO
!        ENDIF
        
!      ENDIF

      IF(IPT.NE.1) THEN
        
        IF(KEXCEL.EQ.0) WRITE(LFPRIN,101)  (PDATA(J),J=1,NV)
        KEXCEL=0D0
        IF(KEXCEL.EQ.1) THEN
         WRITE(LFPRIN,111) BLANK,','
         DO J = 1,NV
         IF(J.LT.NV)  WRITE(LFPRIN,120) PDATA(J),','
         IF(J.EQ.NV)  WRITE(LFPRIN,120) PDATA(J)   !EXCEL
         ENDDO
        ENDIF
        
      ENDIF
                
      ENDDO


100	FORMAT(2X,I5,20E15.6)
 110	FORMAT(I5,A,\)     !EXCEL
 120	FORMAT(E15.6,A,\)  !EXCEL
   
101	FORMAT(2X,5X,20E15.6)
 111  FORMAT(A,\)        !EXCEL


      RETURN
      END
C

C=====================================================================================================================================

!=====================================================================================================================================