
!============================================================================
      SUBROUTINE READFATIGUEDATAINPUT (NFATIGUE)
      
      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT INTEGER*4 (i-n)
      CHARACTER*20 NAME_SCATTER,NAME_HEIGHT,NAME_PERIOD,NAME_MAGNI
      
      DIMENSION WAVE(3),WIND(3)
      DIMENSION VH1(3),VH2(3),VGV(3)
      
        ! AIo = Turbulence Model
        ! ALu = Integral Length Scale  
        ! SD = Standaud Deviation = U10 * Lu 
        
      COMMON /INOU/ ITI 
      
      COMMON /MGRAV/ NGRAV
      COMMON /LINEAT/ KTRAF,KEATH,KCSAL,KOFFL,KSPEC,KDESIGN,KFATM,KFATJ,KFATL,KFAST,KOREV !SONGSAK AUG2007 RESPONSE SPECTRUM FOR ISOLOP 1
      
      COMMON/ FATIGUE / SEABEDRX(1000),WVHIGHTRX(1000),WDEPTHRX(1000),H1POSRX(1000),H2POSRX(1000),
     1                        NRESWAVERX(1000),PERIODRX(1000),GRAVRX(1000),RHOWRX(1000),RHOARX(1000),WKFRX(1000),WFCRX(1000),
     1                        FREQENCYX(1000),DAMPINGX(1000),
     1                        WVHIGHTRX1(1000),WVHIGHTRX2(1000),PERIODRX1(1000),PERIODRX2(1000),SHAPEX1(1000),SHAPEX2(1000),
     1                        TAPX(1000),UCURRENTX(1000),
     1                        NSWINDX(1000),UMEANWINDSPECX(1000),POWERLAWSPECX(1000),ROUGHSPECX(1000),REFERSPECX(1000),
     1                        TURFACTORX(1000),SCALEFACTORX(1000),STDFACTORX(1000),
     1                        VGX(1000,3),V1X(1000,3),V2X(1000,3),VWX(1000,3)
      
      ! ============================================================
      !            CHANA 
      !=============================================================     
      
      COMMON/FATIGUE_OFFSHORE/ NWAVESCAT, NWINDSCAT
      COMMON/WAVE_SCATTER/ NUMSCAT(1000),HSCAT(1000),PERIODSCAT(1000),AMENITUDESCAT(1000)
      COMMON/S_N_CURVE/ AMATERIAL, BMMATERIAL,STRESSEDURANCE,CPAMETER,RPARAMETER
      COMMON/STRESSCONCENTRATION/ ANODESCF(10000) , SCF(10000) 
      COMMON/SCF_NUM/ NUMTOTALSCF
      COMMON/FATIGUE_CODE_CHECK_INTEGER/ IFATIQUECODECHECK , NCRITICALNODE
      COMMON/FATIGUE_CODE_CHECK_REAL/ SFNORMAL , DESIGNFATIGUELIFE
      COMMON/FATIGUE_CODE_CHECK_INTEARRAY/ NUMFATIGUECODECHECK(10000) 
      COMMON/FATIGUE_CODE_CHECK_REALARRAY/ SAFETYFACTOR(10000) 
      
      
      IFATIQUECODECHECK = KFATL 
      
      DO I = 1,NFATIGUE
            
      READ(ITI,*) ! OFFSHORE FATIGUE PARAMETERS CASE 
!     READ(ITI,*) NWAVESCAT , NWINDSCAT , IFATIQUECODECHECK
      READ(ITI,*) SEABEDRX(I),WVHIGHTRX(I),WDEPTHRX(I),H1POSRX(I),H2POSRX(I)
      READ(ITI,*) NRESWAVERX(I),PERIODRX(I),GRAVRX(I),RHOWRX(I),RHOARX(I),WKFRX(I),WFCRX(I)
      READ(ITI,*) WVHIGHTRX1(I),WVHIGHTRX2(I),PERIODRX1(I),PERIODRX2(I),SHAPEX1(I),SHAPEX2(I)
      READ(ITI,*) FREQENCYX(I),DAMPINGX(I)
      READ(ITI,*) UCURRENTX(I),TAPX(I)
      READ(ITI,*) NSWINDX(I),UMEANWINDSPECX(I),POWERLAWSPECX(I),ROUGHSPECX(I),REFERSPECX(I)
      READ(ITI,*) TURFACTORX(I),SCALEFACTORX(I),STDFACTORX(I)
      READ(ITI,*) WAVEANGLE
      READ(ITI,*) WINDANGLE
      
      GRAVRX(I) = ABS(GRAVRX(I))
C     ================================================================ 
C        MODIFY BY TOEY 30-08-2012 FOR WAVE ANGLE AND WIND ANGLE
C     ================================================================
      CALL WAVE_VECTOR (WAVEANGLE,WAVE)
      CALL WIND_VECTOR (WINDANGLE,WIND)
      
      WVZETA = 0.0D0
      WVTIME = 0.0D0
      GRAV = ABS(GRAV)
      
	WAVE(NGRAV) = 0.0D0 !SET WAVE VECTOR IN GRAVITY DIRECTION TO BE ZERO
	WIND(NGRAV) = 0.0D0 !SET WIND VECTOR IN GRAVITY DIRECTION TO BE ZERO

	CALL SCALEN(WAVE,WAVE,DUM,3)
	CALL SCALEN(WIND,WIND,DUM,3)
	
	VGV(1:3)   = 0.0D0
	VGV(NGRAV) = 1.0D0
	VH1(1:3)   = WAVE(1:3)
	
      CALL VECPRD (VGV,VH1,VH2)
	CALL SCALEN(VH2,VH2,DUM,3)

      CALL INTFILL ('UNIT',IUL,1,2,0)
	FAL  = UNITFAC('LENG',IUL,0)
	Z0   = Z0*FAL  !Z0 in (m) unit
C     -------------------------

      VGX(I,1:3)    =   VGV(1:3) 
      V1X(I,1:3)    =   VH1(1:3)
      V2X(I,1:3)    =   VH2(1:3)
      VWX(I,1:3)    =   WIND(1:3)
      
      ENDDO
      
      
      
      READ(ITI,*) NAME_SCATTER,NAME_SCATTER,NAME_SCATTER,NAME_SCATTER,NAME_SCATTER,NWAVESCAT ! WAVE SCATTER DIAGRAM PARAMETER
      READ(ITI,*) NAME_HEIGHT,NAME_HEIGHT,NAME_HEIGHT,HSCAT(1:NWAVESCAT)
      READ(ITI,*) NAME_PERIOD,NAME_PERIOD,PERIODSCAT(1:NWAVESCAT)
      READ(ITI,*) NAME_MAGNI,NAME_MAGNI,AMENITUDESCAT(1:NWAVESCAT)
      
      
      RETURN
      
      IF (KFATM.EQ.1)THEN
      READ(ITI,*) ! S-N CURVE PARAMETER
      READ(ITI,*) AMATERIAL,BMMATERIAL,STRESSEDURANCE,CPAMETER,RPARAMETER,NSNtype
      IF ( NSNtype.NE.33) THEN ! 33 is USER DEFINE.
      !CALL SN_curve_Standard(AMATERIAL,BMMATERIAL,STRESSEDURANCE,CPAMETER,RPARAMETER,NSNtype)
      ENDIF      
      
          !READ(ITI,*) AMATERIAL_JOINT,BMMATERIAL_JOINT,STRESSEDURANCE_JOINT,CPAMETER_JOINT,RPARAMETER_JOINT , NSNtype
          !IF ( NSNtype.NE.33) THEN ! 33 is USER DEFINE.
          !CALL SN_curve_Standard(AMATERIAL_JOINT,BMMATERIAL_JOINT,STRESSEDURANCE_JOINT,CPAMETER_JOINT,RPARAMETER_JOINT,NSNtype)
          !ENDIF
            

      READ(ITI,*) !STRESS CONCENTRATION FACTOR
      READ(ITI,*) NUMTOTALSCF
      READ(ITI,*) !NUM  NODE   SCF
      DO I = 1, NUMTOTALSCF
      READ(ITI,*) ANODESCF(I) ,  SCF(I)  
      ENDDO
      
      READ(ITI,*) !FATIGUE LIFE CODE CHECKING
      READ(ITI,*) NCRITICALNODE
      READ(ITI,*) !NUM  ELE     SF
      
      IF (KFATL.EQ.1)THEN
      DO I = 1, NCRITICALNODE
      READ(ITI,*) NUMFATIGUECODECHECK(I),DESIGNFATIGUELIFE,SFNORMAL,SAFETYFACTOR(I)    
      ENDDO
      ELSEIF(KFATL.NE.1)THEN
      DO I = 1, NCRITICALNODE
      READ(ITI,*) NUMFATIGUECODECHECK(I),SFNORMAL,SAFETYFACTOR(I)    
      ENDDO
      ENDIF
      
      ENDIF
      
      END
      
!=====================================================================================================================

      SUBROUTINE CALLSCATDATA (NDATA,WAVEHEIGHT,WAVEPERIOD,MENITUDE,OFFSELECT,SEABED,WDEPTH,H1POS,H2POS,NRESWAVE,GRAV
     1                         ,RHOW,RHOA,WKF,WFC,FREQENCY,VG,V1,V2,VWIND,DAMPING,NSWIND,UMEANWINDSPEC,POWERLAWSPEC,ROUGHSPEC
     1                         ,REFERSPEC,FWIND,TAP,UCURRENT,WVHIGHTR1,WVHIGHTR2,PERIODR1,PERIODR2,SHAPE1,SHAPE2)
      
      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT INTEGER*4 (i-n)
      
      COMMON/ FATIGUE /       SEABEDRX(1000),WVHIGHTRX(1000),WDEPTHRX(1000),H1POSRX(1000),H2POSRX(1000),
     1                        NRESWAVERX(1000),PERIODRX(1000),GRAVRX(1000),RHOWRX(1000),RHOARX(1000),WKFRX(1000),WFCRX(1000),
     1                        FREQENCYX(1000),DAMPINGX(1000),
     1                        WVHIGHTRX1(1000),WVHIGHTRX2(1000),PERIODRX1(1000),PERIODRX2(1000),SHAPEX1(1000),SHAPEX2(1000),
     1                        TAPX(1000),UCURRENTX(1000),
     1                        NSWINDX(1000),UMEANWINDSPECX(1000),POWERLAWSPECX(1000),ROUGHSPECX(1000),REFERSPECX(1000),
     1                        TURFACTORX(1000),SCALEFACTORX(1000),STDFACTORX(1000),
     1                        VGX(1000,3),V1X(1000,3),V2X(1000,3),VWX(1000,3)
      COMMON/WAVE_SCATTER/ NUMSCAT(1000),HSCAT(1000),PERIODSCAT(1000),AMENITUDESCAT(1000)
      DIMENSION VWAVE(3)
      DIMENSION FWIND(3)
      DIMENSION VG(3),V1(3),V2(3),VWIND(3)
      
      DO I=1,NDATA
      IF (I.EQ.NDATA) THEN
      WAVEHEIGHT = HSCAT(I)
      WAVEPERIOD = PERIODSCAT(I)
      MENITUDE   = AMENITUDESCAT(I)
      ENDIF
      ENDDO
      
      SEABED    = SEABEDRX(OFFSELECT)
      WDEPTH    = WDEPTHRX(OFFSELECT)
      H1POS     = H1POSRX(OFFSELECT)
      H2POS     = H2POSRX(OFFSELECT)
      NRESWAVE  = NRESWAVERX(OFFSELECT)
      GRAV      = GRAVRX(OFFSELECT)
      RHOW      = RHOWRX(OFFSELECT)
      RHOA      = RHOARX(OFFSELECT)
      WKF       = WKFRX(OFFSELECT)
      WFC       = WFCRX(OFFSELECT)
      FREQENCY  = FREQENCYX(OFFSELECT)
      DAMPING   = DAMPINGX(OFFSELECT)
      VG(1:3)   = VGX(OFFSELECT,1:3)
      V1(1:3)   = V1X(OFFSELECT,1:3)
      V2(1:3)   = V2X(OFFSELECT,1:3)
      VWIND(1:3)= VWX(OFFSELECT,1:3)
      
      WVHIGHTR1 = WVHIGHTRX1(OFFSELECT)
      WVHIGHTR2 = WVHIGHTRX2(OFFSELECT)
      PERIODR1  = PERIODRX1(OFFSELECT)
      PERIODR2  = PERIODRX2(OFFSELECT)
      SHAPE1    = SHAPEX1(OFFSELECT)
      SHAPE2    = SHAPEX2(OFFSELECT)
      
      TAP       = TAPX(OFFSELECT)
      UCURRENT  = UCURRENTX(OFFSELECT)
      
      NSWIND        = NSWINDX(OFFSELECT)
      UMEANWINDSPEC  = UMEANWINDSPECX(OFFSELECT)
      POWERLAWSPEC  = POWERLAWSPECX(OFFSELECT)
      ROUGHSPEC     = ROUGHSPECX(OFFSELECT)
      REFERSPEC     = REFERSPECX(OFFSELECT)
      
      FWIND(1)   = TURFACTORX(OFFSELECT)
      FWIND(2)   = SCALEFACTORX(OFFSELECT)
      FWIND(3)   = STDFACTORX(OFFSELECT)
      
      end
      
!=====================================================================================================================

      SUBROUTINE PIC_MAX_STRESS(NDATASCAT)
      
      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT INTEGER*4 (i-n)
      CHARACTER*8 FATIGUEWORD
      CHARACTER*8 FATIGUERESULTWORD
      
      COMMON /ELEM/ NAME(2),ITYPE,ISTYP,NLOPT,MTMOD,NSINC,ITOLEY,
     1              NELE,NMPS,NGPS,NMP,NGP,NNM,NEX,NCO,NNF,NWG,NEFC,
     2              NPT,NWA,NWS,KEG,MEL,NNO,NEF,NELTOT,NMV,MTYP,ISECT
      COMMON/FATIGUE_OFFSHORE/ NWAVESCAT, NWINDSCAT
 !     COMMON /S_N_CURVE/ AMATERIAL, BMMATERIAL,STRESSEDURANCE,CPAMETER,RPARAMETER
      COMMON /WAVE_SCATTER/ NUMSCAT(1000),HSCAT(1000),PERIODSCAT(1000),AMENITUDESCAT(1000)
      COMMON/FATIGUE_CODE_CHECK_INTEGER/ IFATIQUECODECHECK , NCRITICALNODE
      COMMON/FATIGUE_CODE_CHECK_REAL/ SFNORMAL , DESIGNFATIGUELIFE
      COMMON /INOU/ ITI,ITO,ISO,NDATI,NPLOT,NKFAC,NELEM,IFPR(10),IFPL(10)
      COMMON /ChanaSpectrum/ Start , AInterval , Aend   !Chana 2014 RESPONSE SPECTRUM FOR ISOLOP 1
      COMMON /ChanaTImeSeries/ DT  
      COMMON /S_N_CURVE_JOINT/ AMATERIAL_JOINT, BMMATERIAL_JOINT,STRESSEDURANCE_JOINT,CPAMETER_JOINT,RPARAMETER_JOINT       
      
      DIMENSION FREQX(100000),YEARDAMAGE(100000)
      DIMENSION IELEMENTDA(100000)
      
      ALLOCATABLE AMAXELEMENTSECTION(:,:),STRESS(:,:),IELEMENT(:),AMAXSTRESS(:)
     1            ,AMAXSTRESS1(:),AMAXSTRESS2(:)
      
      CALL OFFSHSTEP(TIME,ITIME,NTIME,'CALT') 
            
      ALLOCATE (AMAXELEMENTSECTION(NELE*NWAVESCAT*NTIME,3),STRESS(NELE,12)
     1         ,IELEMENT(NELE),AMAXSTRESS(NELE),AMAXSTRESS1(NELE),AMAXSTRESS2(NELE))
      REWIND(989)
      
      !=========================================
      !ESTABISH   '' PIC_MAX_STRESS.out '' 
      !=========================================
      WRITE(988,*)' ELEMENT , FREQUENCY ,  MAXSTRESS , INDEX '
      IN = 1
      DO N = 1, NWAVESCAT
         DO J = 1, NTIME
         READ (989,*) FREQUENCY 
            DO I = 1, NELE
            READ(989,*)IELEMENT(I),STRESS(I,1:6)
            ENDDO
            DO I = 1, NELE
            READ(989,*)IELEMENT(I),STRESS(I,7:12)
            ENDDO
            DO I = 1, NELE
            AMAXSTRESS1(I) = MAXVAL(STRESS(I,1:12))
            AMAXSTRESS2(I) = ABS(MINVAL(STRESS(I,1:12)))
            IF (AMAXSTRESS1(I).LT.AMAXSTRESS2(I)) AMAXSTRESS(I)  = -AMAXSTRESS2(I)
            IF (AMAXSTRESS1(I).GE.AMAXSTRESS2(I)) AMAXSTRESS(I)  =  AMAXSTRESS1(I)
            AMAXELEMENTSECTION(IN,1) = IELEMENT(I)
            AMAXELEMENTSECTION(IN,3) = AMAXSTRESS(I)    
            FREQX(IN) = FREQUENCY
            WRITE(988,1)IELEMENT(I), FREQUENCY, AMAXSTRESS(I) , IN
1           FORMAT(I5,4X,f12.4,4X,E13.6,4X,I5)
            IN=IN+1
            ENDDO
      
      
C      AMAXSTRESS = MAXVAL(STRESS(:)) 
C      MAXELEMENTSECTION1(IN,1) = IELEMENT
C      FREQX(IN) = FREQUENCY
!     MAXELEMENTSECTION(IN,2) = FREQUENCY
C      MAXELEMENTSECTION1(IN,3) = AMAXSTRESS
C      WRITE(988,1)IELEMENT, FREQUENCY, AMAXSTRESS , IN
C1     FORMAT(I5,4X,f12.4,4X,E13.6,4X,I5)
      !format(3X,I5,4X,I4,2X,F12.4,2X,E12.6,2X,E12.6,2X,E12.6,2X,E12.6,2X,E12.6,2X,E12.6,2X,E12.6,2X,E12.6)
         ENDDO
      ENDDO
      
      !=========================================
      !ESTABISH THE  '' STRESS_SPECTRUM.out '' 
      !=========================================
  
      WRITE(987,*)' INDEX , ELEMENT  , FREQUENCY  ,   SCF ,  MAXSTRESS    ,      dM0   ,    dM2'
      DO N=1,NWAVESCAT
      WRITE(987,*)' SCATTER DATA', N
      DO J=1,NELE
      DO  I = 1, NTIME
      INDEX = J + NELE*(I-1) + NTIME*NELE*(N-1)
      NX   = AMAXELEMENTSECTION( INDEX ,1 ) ! NUMBER OF ELEMENT
      XFRE = FREQX(INDEX)
      XS2   = AMAXELEMENTSECTION( INDEX ,3 ) ! ELEMENT STRESS 
      
      IELEMENTA = NX
      CALL SCF_FACTOR(IELEMENTA,SCFELE)
      
      ! MULTIPLY EFFECTIVE STRESS 
      SCFSTRESS = XS2 * SCFELE
      DM0  = AInterval * SCFSTRESS
      DM2  = AInterval * (XFRE**2D0) * SCFSTRESS
      WRITE(987,3) INDEX , NX ,XFRE , SCFELE , XS2 , DM0 , DM2 
3     FORMAT(I5,4X,I5,4X,4X,f8.4,2X,f8.2,4X,E13.6,4X,E13.6,4X,E13.6)
      ENDDO
      ENDDO
      ENDDO
      
      
      !====================================================
      !ESTABISH THE  '' MOMENT SPECTRUM CALCULATION.out '' 
      !====================================================
      
      REWIND(987)
      
      READ(987,*)
      
      WRITE(2986,1008)
!1008  FORMAT('ELEMENTA ,      SUMDM0 ,       SUMDM2 ,       ATTZ , EFFECTIVE_STRESS ,     DAMAGE ')     
1008  FORMAT('ELEMENTA ,      SUMDM0 ,       SUMDM2 ,       ATTZ ,    DAMAGE ') ! CUTTING  EFFECTIVE_STRESS
      DO N=1,NWAVESCAT
      READ(987,*)
      WRITE(2986,*)' SCATTER DATA', N , 'ENDURANCE STRESS', STRESSEDURANCE_JOINT
      DO J=1,NELE
      
      SUMDM0=0D0
      SUMDM2=0D0
      
      DO I=1,NTIME
      READ(987,*)INDEXNUM,IELEMENTA,FREQM,SCFXX,AMAXSTRESSELE,DMM0,DMM2
      SUMDM0 = SUMDM0 + ABS(DMM0)
      SUMDM2 = SUMDM2 + ABS(DMM2)
      ENDDO
      ATTZ = sqrt(SUMDM0/SUMDM2)
      CALL GAMMA_FUNCTION( (2D0+BMMATERIAL)/2D0 , GA)
      
      ! EFFECTIVE_STRESS CALCULATION
      EFFECTIVE_STRESS = SQRT(8D0*SUMDM0) * (GA**(1/AMATERIAL))
      
      aaa = EFFECTIVE_STRESS
      

      
      !===========================================================================
      ! CALCULATION DAMAGE 
      
       !CALL DAMAGE_CALCULATION(EFFECTIVE_STRESS,AMENITUDESCAT(N),DAMAGE)
!!!      AMAGNITUD =  AMENITUDESCAT(N)
!!!      CALL DAMAGE_CALCULATION(EFFECTIVE_STRESS,AMAGNITUD,DAMAGE)
      
      !============================================================================
      
                  AMAGNITUD = AMENITUDESCAT( N )
                  
                  OccurentNum = AMAGNITUD*(60d0/ATTZ)*60d0*24d0*365.5D0*10**15D0
      
                  
                  IF ( ABS( SUMDM0 ) .GT. STRESSEDURANCE_JOINT) THEN
                  
                      AMATERIAL_CAL =  AMATERIAL_JOINT
                      POWER_M       =  BMMATERIAL_JOINT
                      GINPUT        =  (2D0+POWER_M)/2D0
                      CALL GAMMA_FUNCTION( GINPUT ,GAMMAOUT)
                      
                  ELSE
                  
                      AMATERIAL_CAL =  CPAMETER_JOINT
                      POWER_M       =  RPARAMETER_JOINT  
                      CALL GAMMA_FUNCTION( POWER_M ,GAMMAVALUE)
                      GINPUT        =  (2D0+POWER_M)/2D0
                      CALL GAMMA_FUNCTION( GINPUT ,GAMMAOUT)
                      
                  ENDIF
      
      DAMAGE = OccurentNum*((8D0*ABS( SUMDM0 ))**(POWER_M /2D0))/AMATERIAL_CAL*GAMMAOUT
      
  
      
      !WRITE(2986,5)IELEMENTA , SUMDM0 , SUMDM2 , ATTZ , EFFECTIVE_STRESS , DAMAGE !, SCFELE
      WRITE(2986,5)IELEMENTA , SUMDM0 , SUMDM2 , ATTZ  , DAMAGE ! CUTTING EFFECTIVE_STRESS
      !OPEN(UNIT=2986,FILE='Output_Fatigue/MOMENT_CALCULATION.out'    ,STATUS='UNKNOWN')
5     FORMAT(I5,4X,E13.4,4X,E13.6,4X,F8.6,4X,E13.6,4X,E13.6,4X,F6.3)
      ENDDO
      ENDDO
  
      ! KEED DAMAGE DATE
      REWIND(2986)
      READ(2986,*)
      
      INDEXD = 1D0
      DO I=1,NWAVESCAT !NTIME
      READ(2986,*)
      DO J=1,NELE
      !READ(2986,*)IELEMENTDA(J) , SUMDM0 , SUMDM2 , ATTZ , EFFECTIVE_STRESS , DDAMAGEI
      READ(2986,*)IELEMENTDA(J) , SUMDM0 , SUMDM2 , ATTZ  , DDAMAGEI ! CUTTING EFFECTIVE_STRESS
      YEARDAMAGE(INDEXD)= DDAMAGEI
      INDEXD = INDEXD +1D0
      ENDDO
      ENDDO
      
      IF (IFATIQUECODECHECK.EQ.1D0)THEN
      CLOSE(UNIT=2985,status='DELETE')
      WRITE(2984,*) 
      WRITE(2984,8)   DESIGNFATIGUELIFE
      WRITE(2984,*)
      
      WRITE(ITO,*) 
      WRITE(ITO,8)    DESIGNFATIGUELIFE
      WRITE(ITO,*)
      
      WRITE(10,*) 
      WRITE(10,8)    DESIGNFATIGUELIFE
      WRITE(10,*)
      
      !ITO
      
      
      
8     FORMAT(' DESIGN FATIGUE LIFE   ' , f10.2 )    
      WRITE(2984,*) 'NUM.ELEMNT    S.F    DAMAGE(PERYEAR)   FATIGUE LIVE(YEAR)    UNITY     STATUS'
      WRITE(ITO,*) 'NUM.ELEMNT    S.F    DAMAGE(PERYEAR)   FATIGUE LIVE(YEAR)    UNITY     STATUS'
      WRITE(10,*) 'NUM.ELEMNT    S.F    DAMAGE(PERYEAR)   FATIGUE LIVE(YEAR)    UNITY     STATUS'
      
      DO J=1,NELE
        SUMDA=0
         DO I=1,NWAVESCAT
         INX =  J + NELE*(I-1)
         YEARI = YEARDAMAGE(INX)
         
         SUMDA=SUMDA + YEARI 
   
         FATIGUELIVE = 1D0/SUMDA
         
         IF (SUMDA.EQ.0D0) FATIGUELIVE = 0.0D0
         ENDDO
         
         IELEMENTA = IELEMENTDA(J) 
         CALL FATIGUE_SAFETY_FACTOR(IELEMENTA,SAFETY)
         
         TOTAL_SUMDA = SUMDA * SAFETY
         
         FATIGUELIVE = 1D0/TOTAL_SUMDA
         
         UNITY = DESIGNFATIGUELIFE / FATIGUELIVE
         
         IF( FATIGUELIVE .GT. DESIGNFATIGUELIFE )THEN
             FATIGUERESULTWORD = 'OK '
         ELSE
             FATIGUERESULTWORD = 'NO '
         ENDIF    
             
         IF (FATIGUELIVE.NE.0.0D0)THEN
             
         WRITE(2984,6) IELEMENTDA(J)  ,  SAFETY  ,  TOTAL_SUMDA , FATIGUELIVE , UNITY,  FATIGUERESULTWORD 
         WRITE(ITO,6) IELEMENTDA(J)  ,  SAFETY  ,  TOTAL_SUMDA , FATIGUELIVE , UNITY,  FATIGUERESULTWORD 
         WRITE(10,6) IELEMENTDA(J)  ,  SAFETY  ,  TOTAL_SUMDA , FATIGUELIVE , UNITY,  FATIGUERESULTWORD 
6        FORMAT(I6,6X,F6.1,4X,E12.4,6X,E12.4,6X,F11.3,5X,A10)
         
         ELSEIF (FATIGUELIVE.EQ.0.0D0)THEN 
             
         FATIGUEWORD = 'INFINITY'
         WRITE(2984,7) IELEMENTDA(J) ,  SAFETY ,  SUMDA , FATIGUEWORD ,  FATIGUERESULTWORD
         !!!WRITE(ITO,7) IELEMENTDA(J) ,  SAFETY ,  SUMDA , FATIGUEWORD ,  FATIGUERESULTWORD
7        FORMAT(I6,6X,F6.1,4X,E12.4,6X,A10,4X,A10,12X,A10)   
         
         ENDIF 
      ENDDO
      
      ELSE

         !OPEN(UNIT=2984,FILE='Output_Fatigue/FATIGUE LIFE AND CODE CHECKING.out',STATUS='CLOSE')   

      CLOSE(UNIT=2984,status='DELETE')
          
      WRITE(2985,*) 'NUM.ELEMNT   DAMAGE(PERYEAR)   FATIGUE LIVE (YEAR)'
      WRITE (ITO,*) ''
      WRITE (ITO,*) 'NUM.ELEMNT   DAMAGE(PERYEAR)   FATIGUE LIVE (YEAR)'
      WRITE (10,*) ''
      WRITE (10,*) 'NUM.ELEMNT   DAMAGE(PERYEAR)   FATIGUE LIVE (YEAR)'
          
      DO J=1,NELE
        SUMDA=0
         DO I=1,NWAVESCAT
         INX =  J + NELE*(I-1)
         YEARI = YEARDAMAGE(INX)
         SUMDA=SUMDA + YEARI 
         FATIGUELIVE = 1D0/SUMDA
         IF (SUMDA.EQ.0D0) FATIGUELIVE = 0.0D0
         ENDDO

         IF (FATIGUELIVE.NE.0.0D0)THEN
         WRITE(2985,16) IELEMENTDA(J)  ,  SUMDA , FATIGUELIVE 
         !WRITE(*,16) IELEMENTDA(J)  ,  SUMDA , FATIGUELIVE 
         WRITE (ITO,16) IELEMENTDA(J)  ,  SUMDA , FATIGUELIVE 
         WRITE (10,16) IELEMENTDA(J)  ,  SUMDA , FATIGUELIVE 


16        FORMAT(I6,6X,E12.4,8X,E11.4,4X,E14.6,4X,E13.6)
         ELSEIF (FATIGUELIVE.EQ.0.0D0)THEN 
         FATIGUEWORD = 'INFINITY'
         WRITE(2985,17) IELEMENTDA(J)  ,  SUMDA ,FATIGUEWORD
         WRITE (ITO,17) IELEMENTDA(J)  ,  SUMDA ,FATIGUEWORD
         WRITE (10,17) IELEMENTDA(J)  ,  SUMDA ,FATIGUEWORD
         
17        FORMAT(I6,6X,E12.4,8X,A10)            
         ENDIF 
      ENDDO 

      ENDIF


      DEALLOCATE (AMAXELEMENTSECTION,STRESS,IELEMENT,AMAXSTRESS,AMAXSTRESS1,AMAXSTRESS2)
      
      
    
      END  SUBROUTINE
      
!=================================================================================
      
      SUBROUTINE SCF_FACTOR(IELEMENTA,SCFELE)
      
      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT INTEGER*4 (i-n)
      
      COMMON /ELEM/ NAME(2),ITYPE,ISTYP,NLOPT,MTMOD,NSINC,ITOLEY,
     1              NELE,NMPS,NGPS,NMP,NGP,NNM,NEX,NCO,NNF,NWG,NEFC,
     2              NPT,NWA,NWS,KEG,MEL,NNO,NEF,NELTOT,NMV,MTYP,ISECT
      COMMON/STRESSCONCENTRATION/ ANODESCF(10000) , SCF(10000) 
      COMMON/SCF_NUM/ NUMTOTALSCF
      
      DO  J = 1, NUMTOTALSCF 
          
       ABIDE = ANODESCF(J)    
       SCFNUM = SCF(J)   
       SCFELE = 1D0
      IF ( IELEMENTA .EQ. ABIDE ) THEN
       
          SCFELE = SCFNUM
          
          GOTO 1
      
      ENDIF   
      
      ENDDO
          
1     CONTINUE
      
      RETURN
      END SUBROUTINE
      
!=================================================================================
      
      SUBROUTINE DAMAGE_CALCULATION(EFFECTIVE_STRESS,AMENITUDESCAT,DAMAGE)
      
      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT INTEGER*4 (i-n)
      
      COMMON /S_N_CURVE/ AMATERIAL, BMMATERIAL,STRESSEDURANCE,CPAMETER,RPARAMETER
      ! USING DATA FORM S-N CURVE
      
      IF(ABS(EFFECTIVE_STRESS).LE.STRESSEDURANCE)THEN
      DAMAGE =  AMENITUDESCAT*1000000*(EFFECTIVE_STRESS**RPARAMETER)/CPAMETER 
      ELSE
      DAMAGE =  AMENITUDESCAT*1000000*(EFFECTIVE_STRESS**BMMATERIAL)/AMATERIAL
      ENDIF
      
      RETURN
      END SUBROUTINE
      
!=================================================================================      
      
      SUBROUTINE OUTPUTMAXSTRESS (AF1,MAPP,ISTIME,NGIDM,IGM)
      
      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT INTEGER*4 (i-n)
      
      COMMON /OUTFA/ CHANA,ICHANA,IFATIGUE
      COMMON/FATIGUE_OFFSHORE/ NWAVESCAT, NWINDSCAT
      COMMON /ELEM/ NAME(2),ITYPE,ISTYP,NLOPT,MTMOD,NSINC,ITOLEY,
     1              NELE,NMPS,NGPS,NMP,NGP,NNM,NEX,NCO,NNF,NWG,NEFC,
     2              NPT,NWA,NWS,KEG,MEL,NA,NEF,NELTOT,NMV,MTYP,ISECT
      
	DIMENSION NPM(10),NPI(10),MAPP(10),ASTRESS(12,7)
      DIMENSION AF1(1)
      ! INTIAL SETTING
      ASTRESS(1:5,1:7) = 0.0D0
	!CHANAS1(IGM)= AF1(MAPP(1))
      
	IAX1=MAPP(1)
	IAX2=MAPP(2)
	IAX3=MAPP(3)
	IAX4=MAPP(4)
	IAX5=MAPP(5)
	IAX6=MAPP(6)
	
	DO II=1,5
	
	NMAX1 = IAX1+(II-1)*19D0      !MAPP(1)+((IGM-1)*19*II*2)
	NMAX2 = IAX2+(II-1)*19D0 
	NMAX3 = IAX3+(II-1)*19D0 
	NMAX4 = IAX4+(II-1)*19D0 
	NMAX5 = IAX5+(II-1)*19D0 
	NMAX6 = IAX6+(II-1)*19D0 
	

	ASTRESS(II,1)=  AF1(NMAX1)
	ASTRESS(II,2)=  AF1(NMAX2)
	ASTRESS(II,3)=  AF1(NMAX3)
	ASTRESS(II,4)=  AF1(NMAX4)
	ASTRESS(II,5)=  AF1(NMAX5)
	ASTRESS(II,6)=  AF1(NMAX6)
      
      ENDDO
      
      AMAXSTRESS1 = MAXVAL(ASTRESS(:,1))
	AMAXSTRESS2 = MAXVAL(ASTRESS(:,2))
	AMAXSTRESS3 = MAXVAL(ASTRESS(:,3))
	AMAXSTRESS4 = MAXVAL(ASTRESS(:,4))
	AMAXSTRESS5 = MAXVAL(ASTRESS(:,5))
	AMAXSTRESS6 = MAXVAL(ASTRESS(:,6))
      
      AMAXSTRESS21 = ABS(MINVAL(ASTRESS(:,1)))
	AMAXSTRESS22 = ABS(MINVAL(ASTRESS(:,2)))
	AMAXSTRESS23 = ABS(MINVAL(ASTRESS(:,3)))
	AMAXSTRESS24 = ABS(MINVAL(ASTRESS(:,4)))
	AMAXSTRESS25 = ABS(MINVAL(ASTRESS(:,5)))
	AMAXSTRESS26 = ABS(MINVAL(ASTRESS(:,6)))
      
      IF (AMAXSTRESS1.LT.AMAXSTRESS21) AMAXSTRESS1 = -AMAXSTRESS21 
	IF (AMAXSTRESS2.LT.AMAXSTRESS22) AMAXSTRESS2 = -AMAXSTRESS22 
      IF (AMAXSTRESS3.LT.AMAXSTRESS23) AMAXSTRESS3 = -AMAXSTRESS23 
      IF (AMAXSTRESS4.LT.AMAXSTRESS24) AMAXSTRESS4 = -AMAXSTRESS24 
      IF (AMAXSTRESS5.LT.AMAXSTRESS25) AMAXSTRESS5 = -AMAXSTRESS25 
      IF (AMAXSTRESS6.LT.AMAXSTRESS26) AMAXSTRESS6 = -AMAXSTRESS26 
	
	WRITE(989,991) IGM , AMAXSTRESS1,AMAXSTRESS2,AMAXSTRESS3,AMAXSTRESS4,AMAXSTRESS5,AMAXSTRESS6
	
C	write(991,991) IGM  , AF1(IAX1) , AF1(IAX2) , AF1(IAX3) , AF1(IAX4) , AF1(IAX5), AF1(IAX6) !,MAPP(2),MAPP(3),MAPP(4),MAPP(5),MAPP(6)
991   format(I5,2X,E13.6,2X,E13.6,2X,E13.6,2X,E13.6,2X,E13.6,2X,E13.6,2X,E13.6,2X,E13.6)
      
      ICHANA = ICHANA+1

      
      END SUBROUTINE
      
      !=================================================================================
      !=================================================================================
      
      SUBROUTINE FATIGUE_SAFETY_FACTOR(IELEMENTA,SAFETY)
      
      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT INTEGER*4 (i-n)

      COMMON /ELEM/ NAME(2),ITYPE,ISTYP,NLOPT,MTMOD,NSINC,ITOLEY,
     1              NELE,NMPS,NGPS,NMP,NGP,NNM,NEX,NCO,NNF,NWG,NEFC,
     2              NPT,NWA,NWS,KEG,MEL,NNO,NEF,NELTOT,NMV,MTYP,ISECT
      COMMON/STRESSCONCENTRATION/ ANODESCF(10000) , SCF(10000) 
      COMMON/SCF_NUM/ NUMTOTALSCF
      
      COMMON/FATIGUE_CODE_CHECK_INTEGER/ IFATIQUECODECHECK , NCRITICALNODE
      COMMON/FATIGUE_CODE_CHECK_REAL/ SFNORMAL , DESIGNFATIGUELIFE
      COMMON/FATIGUE_CODE_CHECK_INTEARRAY/ NUMFATIGUECODECHECK(10000) 
      COMMON/FATIGUE_CODE_CHECK_REALARRAY/ SAFETYFACTOR(10000) 
      
      DO  J = 1, NCRITICALNODE
     
       NFACTERNODE = NUMFATIGUECODECHECK(J)   
       SAFETY = SFNORMAL
       
      IF ( IELEMENTA .EQ. NFACTERNODE ) THEN
 
          SAFETY = SAFETYFACTOR(J) 
          
          GOTO 1
      
      ENDIF   
      

      ENDDO
          
1     CONTINUE
      
      RETURN
      END SUBROUTINE
      !=================================================================================
      !=================================================================================
      !=================================================================================      
   