      SUBROUTINE STORAGE_SHELL_THCIKNESS  (NELEMENT,THICKNESS)
      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT INTEGER*4 (I-N)
      COMMON/SHELL_THICKNESS/ SHELL_THICKNESS(80000)
      SHELL_THICKNESS(NELEMENT) = THICKNESS
      END
C  ========================================================================================================
      SUBROUTINE CALLING_SHELL_THCIKNESS  (NELEMENT,THICKNESS)
      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT INTEGER*4 (I-N)
      COMMON/SHELL_THICKNESS/ SHELL_THICKNESS(80000)
      
      THICKNESS = SHELL_THICKNESS(NELEMENT)
      END