!      SUBROUTINE DEFINDLOCALSTRESS_GID (NELEMENT,OPT,HED,NAMEHEAD,NAML,JSTEP) 
!      IMPLICIT REAL*8 (A-H,O-Z)
!      IMPLICIT INTEGER*4 (I-N)
!      CHARACTER*4 OPT
!      CHARACTER*200 NAMEHEAD,NAMEG
!	CHARACTER*3 METHOD
!	CHARACTER(3)  HED
!      COMMON /XFPOUT/ KEXCEL,LFPRIN,LFPRN1,LFPRN2,LFPRN3,LFPRN4
!      COMMON / FRAMEFORCE / AR(30),NELEMENTT
!      COMMON /ELEM/ NAME(2),ITYPE,ISTYP,NLOPT,MTMOD,NSINC,ITOLEY,
!     1              NELE,NMPS,NGPS,NMP,NGP,NNM,NEX,NCO,NNF,NWG,NEFC,
!     2              NPT,NWA,NWS,KEG,MEL,NNO,NEF,NELTOT,NMV,MTYP,ISECT
!      COMMON / SECTIONDETAIL / BFISHAPE,TFISHAPE,DISHAPE,BWISHAPE,TWISHAPE,ROOTISHAPE
!     1                        ,BFHSHAPE,TFHSHAPE,DHSHAPE,BWHSHAPE,TWHSHAPE,ROOTHSHAPE
!     1                        ,BANGLE,TANGLE,HANGLE,THANGLE,AXBAR
!     1                        ,BFCHANNEL,TFCHANNEL,DCHANNEL,TWCHANNEL,HCHANNEL,ROOTCSHAPE,CXBAR
!     1                        ,BFTSHAPE,TFTSHAPE,DTSHAPE,BWTSHAPE,TWTSHAPE,TYBAR
!     1                        ,BBOX,TFBOX,DBOX,HBOX,TWBOX,ROOTBOX
!     1                        ,DPIPE,TPIPE
!     1                        ,DROUND
!     1                        ,BREC,HREC
!     1                        ,SECTIONT,SECTIONS,AJ,GSECTION,CW,AREA,AIS,AIT,ARGS,ARGT
!     1                        ,PLASTICT,PLASTICS,AMODULUS
!      COMMON /LOCAL_STRESS/ AXIAL(5,10000),SHEARS(5,10000),SHEART(5,10000),ATORSION(5,10000),AMOMENTS(5,10000),AMOMENTT(5,10000)
!      
!      IF (OPT.EQ."HEAD")THEN
!      WRITE (LFPRIN,1000) HED,NAMEHEAD(1:NAML),JSTEP
!      
!      ELSEIF (OPT.EQ."CLEA")THEN
!                
!      AXIAL    = 0.
!      SHEARS   = 0.
!      SHEART   = 0.
!      ATORSION = 0.
!      AMOMENTS = 0.
!      AMOMENTT = 0.
!      
!      ELSEIF (OPT.EQ."BODY")THEN
!          
!       CALL ARRAYELEMENT (NELEMENT,NSECTION)
!       IF (NSECTION.EQ.0)  RETURN 
!       IF (NSECTION.GT.22) RETURN
!
!       AXIAL(1,NELEMENT)    = AR(1)  /AREA
!       AXIAL(2,NELEMENT)    = AR(7)  /AREA
!       AXIAL(3,NELEMENT)    = AR(13) /AREA
!       AXIAL(4,NELEMENT)    = AR(19) /AREA
!       AXIAL(5,NELEMENT)    = AR(25) /AREA
!       
!       SHEARS(1,NELEMENT)   = 2D0*AR(2)  /AREA
!       SHEARS(2,NELEMENT)   = 2D0*AR(8)  /AREA
!       SHEARS(3,NELEMENT)   = 2D0*AR(14) /AREA
!       SHEARS(4,NELEMENT)   = 2D0*AR(20) /AREA
!       SHEARS(5,NELEMENT)   = 2D0*AR(26) /AREA
!      
!       SHEART(1,NELEMENT)   = 2D0*AR(3)  /AREA
!       SHEART(2,NELEMENT)   = 2D0*AR(9)  /AREA
!       SHEART(3,NELEMENT)   = 2D0*AR(15) /AREA
!       SHEART(4,NELEMENT)   = 2D0*AR(21) /AREA
!       SHEART(5,NELEMENT)   = 2D0*AR(27) /AREA
!       
!       IF (NSECTION.EQ.21) C = DPIPE  /2D0
!       IF (NSECTION.EQ.22) C = DROUND /2D0
!       IF (NSECTION.EQ.23) C = DROUND /2D0
!      
!       ATORSION(1,NELEMENT) = AR(4) *C /AJ
!       ATORSION(2,NELEMENT) = AR(10)*C /AJ
!       ATORSION(3,NELEMENT) = AR(16)*C /AJ
!       ATORSION(4,NELEMENT) = AR(22)*C /AJ
!       ATORSION(5,NELEMENT) = AR(28)*C /AJ
!       
!       AMOMENTS(1,NELEMENT) = AR(5)  /SECTIONT
!       AMOMENTS(2,NELEMENT) = AR(11) /SECTIONT
!       AMOMENTS(3,NELEMENT) = AR(17) /SECTIONT
!       AMOMENTS(4,NELEMENT) = AR(23) /SECTIONT
!       AMOMENTS(5,NELEMENT) = AR(29) /SECTIONT
!      
!       AMOMENTT(1,NELEMENT) = AR(6)  /SECTIONT
!       AMOMENTT(2,NELEMENT) = AR(12) /SECTIONT
!       AMOMENTT(3,NELEMENT) = AR(18) /SECTIONT
!       AMOMENTT(4,NELEMENT) = AR(24) /SECTIONT
!       AMOMENTT(5,NELEMENT) = AR(30) /SECTIONT
!       
!      ELSEIF (OPT.EQ."WRIT")THEN
!          
!      DO NELEMENT = 1,NELE
!       DO I = 1,5
!         IF (I.EQ.1) WRITE (LFPRIN,101) NELEMENT,AXIAL(I,NELEMENT),SHEARS(I,NELEMENT),SHEART(I,NELEMENT)
!     1                     ,ATORSION(I,NELEMENT),AMOMENTS(I,NELEMENT),AMOMENTT(I,NELEMENT)
!         IF (I.NE.1) WRITE (LFPRIN,100) AXIAL(I,NELEMENT),SHEARS(I,NELEMENT),SHEART(I,NELEMENT)
!     1                     ,ATORSION(I,NELEMENT),AMOMENTS(I,NELEMENT),AMOMENTT(I,NELEMENT)
!       ENDDO
!       ENDDO
!       
!       WRITE (LFPRIN,102)
!      ENDIF
!      
!100   FORMAT (7X,E12.5,2X,E12.5,2X,E12.5,2X,E12.5,2X,E12.5,2X,E12.5)      
!101   FORMAT (I5,2X,E12.5,2X,E12.5,2X,E12.5,2X,E12.5,2X,E12.5,2X,E12.5)
!102   FORMAT ("End Values")
!      
!1000	FORMAT(/'Result "XFrame-Local-Stress ',A3,'"',2X,
!	1	    '"',A,'"',
!	1		2X,I5,2X,'Matrix',2X,'OnGaussPoints',2X,'"XFrame"'/,
!	2		'ComponentNames',
!     3		' "Axial-Stress" "Shear Stress-S" "Shear Stress-T"',
!	4		' "Torsional Stress" "Bending Stress-S" "Bending Stress-T"'/,
!	5		'Values')
!      
!      END