C	==================================================================
      SUBROUTINE FLOOR_AREA_SPAN (AREA_OUT1,AREA_OUT2)
      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT INTEGER*4 (i-n)
      COMMON /DIAPH_DATA/ NSLAVE_NODE(500,100),NSLAVE(500)
      COMMON /FLOOR/ IFLOOR,NFLOOR,NSN0
      COMMON /MGRAV/ NGRAV
      DIMENSION AREA_OUT1(IFLOOR),AREA_OUT2(IFLOOR)
      DIMENSION FLOOR_MID_ELEVATION(IFLOOR)
      ALLOCATABLE NSLAVE_NODE_FLOOR(:),A1(:),A2(:),ELEVATION(:)
      ALLOCATABLE A1_LENGTH_FLOOR(:),A2_LENGTH_FLOOR(:),ELEVATION_LENGTH_FLOOR(:)
      
      ! FLOOR PROJECTED AREA
      ALLOCATE (A1_LENGTH_FLOOR(IFLOOR),A2_LENGTH_FLOOR(IFLOOR),ELEVATION_LENGTH_FLOOR(IFLOOR))
      DO I = 1,IFLOOR
         ALLOCATE (NSLAVE_NODE_FLOOR(NSLAVE(I)),A1(NSLAVE(I)),A2(NSLAVE(I)),ELEVATION(NSLAVE(I)))
         A1 = 0.
         A2 = 0.
         ELEVATION = 0.
         NSLAVE_NODE_FLOOR = 0.
         NSLAVE_NODE_FLOOR(1:NSLAVE(I)) = NSLAVE_NODE(I,1:NSLAVE(I))
         
         DO J = 1,NSLAVE(I)
         SELECTCASE (NGRAV)
         CASE (1) ! X-DIRECTION
         CALL RELFILL('@XYZ',ELEVATION(I),1,NSLAVE_NODE_FLOOR(J),0)  !GETTING NODAL COORDINATE
	   CALL RELFILL('@XYZ',A1(J),2,NSLAVE_NODE_FLOOR(J),0)         !GETTING NODAL COORDINATE
	   CALL RELFILL('@XYZ',A2(J),3,NSLAVE_NODE_FLOOR(J),0)         !GETTING NODAL COORDINATE
         CASE (2) ! Y-DIRECTION  
         CALL RELFILL('@XYZ',A1(J),1,NSLAVE_NODE_FLOOR(J),0)         !GETTING NODAL COORDINATE
	   CALL RELFILL('@XYZ',ELEVATION(I),2,NSLAVE_NODE_FLOOR(J),0)  !GETTING NODAL COORDINATE
	   CALL RELFILL('@XYZ',A2(J),3,NSLAVE_NODE_FLOOR(J),0)         !GETTING NODAL COORDINATE
         CASE (3) ! Z-DIRECTION
         CALL RELFILL('@XYZ',A1(J),1,NSLAVE_NODE_FLOOR(J),0)         !GETTING NODAL COORDINATE
	   CALL RELFILL('@XYZ',A2(J),2,NSLAVE_NODE_FLOOR(J),0)         !GETTING NODAL COORDINATE
	   CALL RELFILL('@XYZ',ELEVATION(J),3,NSLAVE_NODE_FLOOR(J),0)  !GETTING NODAL COORDINATE
         ENDSELECT 
         ENDDO
         
         ! FLOOR PROJECTED AREA
         COOR_MAX_A1_FLOOR        = MAXVAL(A1)
         COOR_MAX_A2_FLOOR        = MAXVAL(A2)
         COOR_MAX_ELEVATION_FLOOR = MAXVAL(ELEVATION)
         
         COOR_MIN_A1_FLOOR        = MAXVAL(A1)
         COOR_MIN_A2_FLOOR        = MAXVAL(A2)
         COOR_MIN_ELEVATION_FLOOR = MAXVAL(ELEVATION) 
         
         A1_LENGTH_FLOOR(I) = COOR_MAX_A1_FLOOR - COOR_MIN_A1_FLOOR
         A2_LENGTH_FLOOR(I) = COOR_MAX_A2_FLOOR - COOR_MIN_A2_FLOOR
         ELEVATION_LENGTH_FLOOR(I) = COOR_MAX_ELEVATION_FLOOR - COOR_MIN_ELEVATION_FLOOR
         IF (COOR_MAX_A1_FLOOR.EQ.COOR_MIN_A1_FLOOR) A1_LENGTH_FLOOR(I) = COOR_MAX_A1_FLOOR
         IF (COOR_MAX_A2_FLOOR.EQ.COOR_MIN_A2_FLOOR) A2_LENGTH_FLOOR(I) = COOR_MAX_A2_FLOOR
         IF (COOR_MAX_ELEVATION_FLOOR.EQ.COOR_MIN_ELEVATION_FLOOR) ELEVATION_LENGTH_FLOOR(I) = COOR_MAX_ELEVATION_FLOOR
      
         
         DEALLOCATE (NSLAVE_NODE_FLOOR,A1,A2,ELEVATION)
      ENDDO
      
      ! CALCULATE PROJECTED AREA EACH FLOOR
      AREA_OUT1 = 0.
      AREA_OUT2 = 0.
      DO I =1,IFLOOR
         IF (I.EQ.1)         THEN ! FIRST FLOOR
         ELEVATION_FLOOR        = ELEVATION_LENGTH_FLOOR(I+1) - ELEVATION_LENGTH_FLOOR(I)
         AREA_OUT1(I)           = A1_LENGTH_FLOOR(I)*ELEVATION_FLOOR
         AREA_OUT2(I)           = A2_LENGTH_FLOOR(I)*ELEVATION_FLOOR
         ELSEIF (I.EQ.IFLOOR)THEN ! LAST FLOOR
         ELEVATION_FLOOR        = ELEVATION_LENGTH_FLOOR(I) - ELEVATION_LENGTH_FLOOR(I-1)
         AREA_OUT1(I)           = A1_LENGTH_FLOOR(I)*ELEVATION_FLOOR
         AREA_OUT2(I)           = A2_LENGTH_FLOOR(I)*ELEVATION_FLOOR
         ELSEIF (I.NE.1)     THEN
         ELEVATION_FLOOR        = ELEVATION_LENGTH_FLOOR(I+1) - ELEVATION_LENGTH_FLOOR(I)
         AREA_OUT1(I)           = A1_LENGTH_FLOOR(I)*ELEVATION_FLOOR
         AREA_OUT2(I)           = A2_LENGTH_FLOOR(I)*ELEVATION_FLOOR
         ENDIF
      ENDDO
      
      DEALLOCATE (A1_LENGTH_FLOOR,A2_LENGTH_FLOOR,ELEVATION_LENGTH_FLOOR)
      
      END