      SUBROUTINE WIND_EUROCODE_1997 (IOPT_WIND)
      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT INTEGER*4 (i-n)
      COMMON /INOU/ ITI,ITO,ISO,NDATI,NPLOT,NKFAC,NELEM,
     1              IFPR(10),IFPL(10)
      
      SELECTCASE(IOPT_WIND)
      CASE (7) ! SIMPLIFIED PROCEDURE
      READ (ITI,*) IOPT_ROUGNESS,V_WIND,WIND_COEFF,ALEE_COEFF,FRIC_COEFF,IOPT_TOPO,CT,VER_CT,IOPT_FORCE,FORCE_COEFF
     1             ,DIREC_COFF1,DIREC_COFF2
      
      CT = CT + 0.001D0*VER_CT
      IF (IOPT_TOPO.EQ.0) CT = 1.0D0
      IF (IOPT_FORCE.EQ.0) IOPT_FORCE = 1.0D0
      IF (FORCE_COEFF.EQ.0) FORCE_COEFF = 1.0D0
      CALL STORY_SIMPLIFIED_EURO_1997 (IOPT_ROUGNESS,CT,V_WIND,FRIC_COEFF,WIND_COEFF,ALEE_COEFF,FORCE_COEFF,DIREC_COFF1,DIREC_COFF2)
      
      IF (IOPT_ADD_WIND.EQ.1) CALL WIND_ADD_FORCE (ITO_ADD)
      
      CASE (8) ! DETAIL PROCEDURE
          
      READ (ITI,*) IOPT_ROUGNESS,V_WIND,WIND_COEFF,ALEE_COEFF,FRIC_COEFF,IOPT_TOPO,CT,VER_CT,IOPT_FORCE,FORCE_COEFF,GUST_FACTOR
     1             ,DIREC_COFF1,DIREC_COFF2
      
      CT = CT + 0.001D0*VER_CT
      IF (IOPT_TOPO.EQ.0) CT = 1.0D0
      IF (IOPT_FORCE.EQ.0) IOPT_FORCE = 1.0D0
      IF (FORCE_COEFF.EQ.0) FORCE_COEFF = 1.0D0
      CALL STORY_DETAILED_EURO_1997 (IOPT_ROUGNESS,CT,V_WIND,FRIC_COEFF,WIND_COEFF,ALEE_COEFF,GUST_FACTOR,FORCE_COEFF
     1                              ,DIREC_COFF1,DIREC_COFF2)
      
      IF (IOPT_ADD_WIND.EQ.1) CALL WIND_ADD_FORCE (ITO_ADD)
      
      ENDSELECT
      
      END
C	==================================================================
      SUBROUTINE STORY_SIMPLIFIED_EURO_1997 (IOPT_ROUGNESS,CT,V_WIND,FRIC_COEFF,WIND_COEFF,ALEE_COEFF,FORCE_COEFF
     1                                      ,DIREC_COFF1,DIREC_COFF2)
      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT INTEGER*4 (i-n)
      COMMON /FLOOR/ IFLOOR,NFLOOR,NSN0
      COMMON /MGRAV/ NGRAV
      COMMON /WIND_LATERAL/ WIND_D(3,10000),WIND_CASE(500),IN_FLOOR
      DIMENSION AREA_OUT1(IFLOOR),AREA_OUT2(IFLOOR)
      DIMENSION ELEVATION(IFLOOR)
      DIMENSION FORCE1(IFLOOR),FORCE2(IFLOOR),PF_F(IFLOOR)
      DIMENSION FORCE_FRICTION1(IFLOOR),FORCE_FRICTION2(IFLOOR)
      AREA_OUT1 = 0.
      AREA_OUT2 = 0.
      FORCE1    = 0.
      FORCE2    = 0.
      CALL FLOOR_AREA_SPAN (AREA_OUT1,AREA_OUT2)
      CALL L_B_LENGTH (RATIO_L,RATIO_B,ELEVATION)
      
      CALL ROUGHNESS_FACTOR_EURO_1997 (IOPT_ROUGNESS,AKR,ZO,ZMIN)
      
      AREA      = 0.
      DO I = 1,IFLOOR ! 1FT
      IF (I.NE.IFLOOR-1) ELEVATION_CAL = ELEVATION(I)
      IF (I.EQ.IFLOOR-1) ELEVATION_CAL = ELEVATION(IFLOOR)   
      ! CALCULATE ACR
      AKR  = 0.19D0*((ZO/0.05D0)**(0.07D0))
      ZMAX = 200D0
      IF (ELEVATION_CAL.GE.ZMIN.AND.ELEVATION_CAL.LE.ZMAX)THEN
         ACR = AKR*LOG(ELEVATION_CAL/ZO)  
      ELSEIF (ELEVATION_CAL.LE.ZMIN)THEN
         ACR = AKR*LOG(ZMIN/ZO) 
      ENDIF
      
      ! EXPOSURE COEFFICIENT
      CE  = ACR**2D0 * CT**2D0 * (1D0+1.4D0/(ACR*CT))
      ! REFERENCE MEAN WIND SPEED
      QREF = 0.5D0 * 0.1276D0 * V_WIND**2D0
      ! FRICTIONAL WIND PRESSURE IN SIDE WALL
      PF_F(I) = FRIC_COEFF * CE * QREF
      PF_F(I) = PF_F(I)*9.806D0 ! UNIT KG > N
      ! NET WIND PRESSURE ACROSS A SURFACE
      PF   = (WIND_COEFF-ALEE_COEFF) * CE * QREF
      PF   = PF *9.806D0 ! UNIT KG > N

      ENDDO
      
      DO I = 1,IFLOOR 
       IF (I.EQ.1.OR.I.EQ.IFLOOR)THEN
       FORCE_FRICTION1(I) = PF_F(I)*AREA_OUT1(I)
       ELSEIF (I.NE.1)THEN
       FORCE_FRICTION1(I) = (PF_F(I)*AREA_OUT1(I))+(PF_F(I-1)*AREA_OUT1(I-1))
       ENDIF
       FORCE1(I) = PF*AREA_OUT2(I)*DIREC_COFF1*FORCE_COEFF
      ENDDO
      
      PF_F = 0.D0
      DO I = 1,IFLOOR ! 2ND >
      ELEVATION_CAL = ELEVATION(IFLOOR)   
      ! CALCULATE ACR
      AKR  = 0.19D0*((ZO/0.05D0)**(0.07D0))
      ZMAX = 200D0
      IF (ELEVATION_CAL.GE.ZMIN.AND.ELEVATION_CAL.LE.ZMAX)THEN
         ACR = AKR*LOG(ELEVATION_CAL/ZO)  
      ELSEIF (ELEVATION_CAL.LE.ZMIN)THEN
         ACR = AKR*LOG(ZMIN/ZO) 
      ENDIF
      
      ! EXPOSURE COEFFICIENT
      CE  = ACR**2D0 * CT**2D0 * (1D0+1.4D0/(ACR*CT))
      ! REFERENCE MEAN WIND SPEED
      QREF = 0.5D0 * 0.1276D0 * V_WIND**2D0
      ! FRICTIONAL WIND PRESSURE IN SIDE WALL
      PF_F(I) = FRIC_COEFF * CE * QREF
      PF_F(I) = PF_F(I)*9.806D0 ! UNIT KG > N
      ! NET WIND PRESSURE ACROSS A SURFACE
      PF   = (WIND_COEFF-ALEE_COEFF) * CE * QREF
      PF   = PF *9.806D0 ! UNIT KG > N
      

      ENDDO
      
      DO I = 1,IFLOOR ! CALCULATE FRICTION FORCE
       IF (I.EQ.1.OR.I.EQ.IFLOOR)THEN
       FORCE_FRICTION2(I) = PF_F(I)*AREA_OUT2(I)
       ELSEIF (I.NE.1)THEN
       FORCE_FRICTION2(I) = (PF_F(I)*AREA_OUT2(I))+(PF_F(I-1)*AREA_OUT2(I-1))
       ENDIF
       FORCE2(I) = PF*AREA_OUT1(I)*DIREC_COFF1*FORCE_COEFF
      ENDDO
      
      DO I = 1,IFLOOR
      SELECTCASE(NGRAV)
      CASE(1)
        IN_FLOOR           = IN_FLOOR + 1
        IF (I.EQ.1.OR.I.EQ.IFLOOR) THEN
        WIND_D(1,IN_FLOOR) = 0.0D0
        WIND_D(2,IN_FLOOR) = FORCE1(I)/2D0 + FORCE_FRICTION1(I)
        WIND_D(3,IN_FLOOR) = FORCE2(I)/2D0 + FORCE_FRICTION2(I)
        ELSEIF (I.NE.1) THEN
        WIND_D(1,IN_FLOOR) = 0.0D0
        WIND_D(2,IN_FLOOR) = (FORCE1(I) + FORCE1(I-1))/2D0 + FORCE_FRICTION1(I)
        WIND_D(3,IN_FLOOR) = (FORCE2(I) + FORCE2(I-1))/2D0 + FORCE_FRICTION2(I)
        ENDIF
      CASE(2)
        IN_FLOOR           = IN_FLOOR + 1
        IF (I.EQ.1.OR.I.EQ.IFLOOR) THEN
        WIND_D(1,IN_FLOOR) = FORCE1(I)/2D0
        WIND_D(2,IN_FLOOR) = 0.0D0
        WIND_D(3,IN_FLOOR) = FORCE2(I)/2D0
        ELSEIF (I.NE.1) THEN
        WIND_D(1,IN_FLOOR) = (FORCE1(I) + FORCE1(I-1))/2D0 + FORCE_FRICTION1(I)
        WIND_D(2,IN_FLOOR) = 0.0D0
        WIND_D(3,IN_FLOOR) = (FORCE2(I) + FORCE2(I-1))/2D0 + FORCE_FRICTION2(I)
        ENDIF
      CASE(3)
        IN_FLOOR           = IN_FLOOR + 1
        IF (I.EQ.1.OR.I.EQ.IFLOOR) THEN
        WIND_D(1,IN_FLOOR) = FORCE1(I)/2D0
        WIND_D(2,IN_FLOOR) = 0.0D0
        WIND_D(3,IN_FLOOR) = FORCE2(I)/2D0
        ELSEIF (I.NE.1) THEN
        WIND_D(1,IN_FLOOR) = (FORCE1(I) + FORCE1(I-1))/2D0 + FORCE_FRICTION1(I)
        WIND_D(2,IN_FLOOR) = (FORCE2(I) + FORCE2(I-1))/2D0 + FORCE_FRICTION2(I)
        WIND_D(3,IN_FLOOR) = 0.0D0
        ENDIF
      ENDSELECT
      ENDDO
      
      END
      
C	==================================================================
      SUBROUTINE STORY_DETAILED_EURO_1997 (IOPT_ROUGNESS,CT,V_WIND,FRIC_COEFF,WIND_COEFF,ALEE_COEFF,GUST_FACTOR
     1                                    ,FORCE_COEFF,DIREC_COFF1,DIREC_COFF2)
      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT INTEGER*4 (i-n)
      COMMON /FLOOR/ IFLOOR,NFLOOR,NSN0
      COMMON /MGRAV/ NGRAV
      COMMON /WIND_LATERAL/ WIND_D(3,10000),WIND_CASE(500),IN_FLOOR
      DIMENSION AREA_OUT1(IFLOOR),AREA_OUT2(IFLOOR)
      DIMENSION ELEVATION(IFLOOR)
      DIMENSION FORCE1(IFLOOR),FORCE2(IFLOOR)
      DIMENSION PF_F(IFLOOR)
      DIMENSION FORCE_FRICTION1(IFLOOR),FORCE_FRICTION2(IFLOOR)
      
      AREA_OUT1 = 0.
      AREA_OUT2 = 0.
      FORCE1    = 0.
      FORCE2    = 0.
      
      CALL FLOOR_AREA_SPAN (AREA_OUT1,AREA_OUT2)
      CALL L_B_LENGTH (RATIO_L,RATIO_B,ELEVATION)
      
      CALL ROUGHNESS_FACTOR_EURO_1997 (IOPT_ROUGNESS,AKR,ZO,ZMIN)
      
      DO I = 1,IFLOOR ! 1FT
      IF (I.NE.IFLOOR-1) ELEVATION_CAL = ELEVATION(I)
      IF (I.EQ.IFLOOR-1) ELEVATION_CAL = ELEVATION(IFLOOR)   
      ! CALCULATE ACR
      AKR  = 0.19D0*((ZO/0.05D0)**(0.07D0))
      ZMAX = 200D0
      IF (ELEVATION_CAL.GE.ZMIN.AND.ELEVATION_CAL.LE.ZMAX)THEN
         ACR = AKR*LOG(ELEVATION_CAL/ZO)  
      ELSEIF (ELEVATION_CAL.LE.ZMIN)THEN
         ACR = AKR*LOG(ZMIN/ZO) 
      ENDIF
      
      ! EXPOSURE COEFFICIENT
      CE  = ACR**2D0 * CT**2D0 * (1D0+1.4D0/(ACR*CT))
      ! REFERENCE MEAN WIND SPEED
      QREF = 0.5D0 * 0.1276D0 * V_WIND**2D0
      ! FRICTIONAL WIND PRESSURE IN SIDE WALL
      PF_F(I) = FRIC_COEFF * CE * QREF
      PF_F(I) = PF_F(I)*9.806D0 ! UNIT KG > N
      
      CO   = 1.0D0
      VM   = ACR * CO * V_WIND
      
      ! DESIGN VELOCITY PRESSURE
      QB   = 0.5D0*1.25D0*(VM**2D0)
      
      ! NET WIND PRESSURE ACROSS A SURFACE
      PF   = (WIND_COEFF-ALEE_COEFF) * CE * QB
      PF   = PF *9.806D0 ! UNIT KG > N
      
      ENDDO
      
      ! CALCULATE FRICTION FORCE
      DO I = 1,IFLOOR 
       IF (I.EQ.1.OR.I.EQ.IFLOOR)THEN
       FORCE_FRICTION1(I) = PF_F(I)*AREA_OUT1(I)
       ELSEIF (I.NE.1)THEN
       FORCE_FRICTION1(I) = (PF_F(I)*AREA_OUT1(I))+(PF_F(I-1)*AREA_OUT1(I-1))
       ENDIF
       FORCE1(I) = PF*AREA_OUT2(I)*DIREC_COFF1*FORCE_COEFF
      ENDDO
      
      DO I = 1,IFLOOR ! 2ND > 
      IF (I.NE.IFLOOR-1) ELEVATION_CAL = ELEVATION(I)
      IF (I.EQ.IFLOOR-1) ELEVATION_CAL = ELEVATION(IFLOOR)   
      ! CALCULATE ACR
      AKR  = 0.19D0*((ZO/0.05D0)**(0.07D0))
      ZMAX = 200D0
      IF (ELEVATION_CAL.GE.ZMIN.AND.ELEVATION_CAL.LE.ZMAX)THEN
         ACR = AKR*LOG(ELEVATION_CAL/ZO)  
      ELSEIF (ELEVATION_CAL.LE.ZMIN)THEN
         ACR = AKR*LOG(ZMIN/ZO) 
      ENDIF
      
      ! EXPOSURE COEFFICIENT
      CE  = ACR**2D0 * CT**2D0 * (1D0+1.4D0/(ACR*CT))
      ! REFERENCE MEAN WIND SPEED
      QREF = 0.5D0 * 0.1276D0 * V_WIND**2D0
      ! FRICTIONAL WIND PRESSURE IN SIDE WALL
      PF_F(I) = FRIC_COEFF * CE * QREF
      PF_F(I) = PF_F(I)*9.806D0 ! UNIT KG > N
      
      CO   = 1.0D0
      VM   = ACR * CO * V_WIND
      
      ! DESIGN VELOCITY PRESSURE
      QB   = 0.5D0*1.25D0*(VM**2D0)
      
      ! NET WIND PRESSURE ACROSS A SURFACE
      PF   = (WIND_COEFF-ALEE_COEFF) * CE * QB
      PF   = PF *9.806D0 ! UNIT KG > N
      
      ENDDO
      
      ! CALCULATE FRICTION FORCE
      DO I = 1,IFLOOR ! CALCULATE FRICTION FORCE
       IF (I.EQ.1.OR.I.EQ.IFLOOR)THEN
       FORCE_FRICTION2(I) = PF_F(I)*AREA_OUT2(I)
       ELSEIF (I.NE.1)THEN
       FORCE_FRICTION2(I) = (PF_F(I)*AREA_OUT2(I))+(PF_F(I-1)*AREA_OUT2(I-1))
       ENDIF
       FORCE2(I) = PF*AREA_OUT1(I)*DIREC_COFF1*FORCE_COEFF
      ENDDO
      
      DO I = 1,IFLOOR
      SELECTCASE(NGRAV)
      CASE(1)
        IN_FLOOR           = IN_FLOOR + 1
        IF (I.EQ.1.OR.I.EQ.IFLOOR) THEN
        WIND_D(1,IN_FLOOR) = 0.0D0
        WIND_D(2,IN_FLOOR) = FORCE1(I)/2D0 + FORCE_FRICTION1(I)
        WIND_D(3,IN_FLOOR) = FORCE2(I)/2D0 + FORCE_FRICTION2(I)
        ELSEIF (I.NE.1) THEN
        WIND_D(1,IN_FLOOR) = 0.0D0
        WIND_D(2,IN_FLOOR) = (FORCE1(I) + FORCE1(I-1))/2D0 + FORCE_FRICTION1(I)
        WIND_D(3,IN_FLOOR) = (FORCE2(I) + FORCE2(I-1))/2D0 + FORCE_FRICTION2(I)
        ENDIF
      CASE(2)
        IN_FLOOR           = IN_FLOOR + 1
        IF (I.EQ.1.OR.I.EQ.IFLOOR) THEN
        WIND_D(1,IN_FLOOR) = FORCE1(I)/2D0 + FORCE_FRICTION1(I)
        WIND_D(2,IN_FLOOR) = 0.0D0
        WIND_D(3,IN_FLOOR) = FORCE2(I)/2D0 + FORCE_FRICTION2(I)
        ELSEIF (I.NE.1) THEN
        WIND_D(1,IN_FLOOR) = (FORCE1(I) + FORCE1(I-1))/2D0 + FORCE_FRICTION1(I)
        WIND_D(2,IN_FLOOR) = 0.0D0
        WIND_D(3,IN_FLOOR) = (FORCE2(I) + FORCE2(I-1))/2D0 + FORCE_FRICTION2(I)
        ENDIF
      CASE(3)
        IN_FLOOR           = IN_FLOOR + 1
        IF (I.EQ.1.OR.I.EQ.IFLOOR) THEN
        WIND_D(1,IN_FLOOR) = FORCE1(I)/2D0 + FORCE_FRICTION1(I)
        WIND_D(2,IN_FLOOR) = 0.0D0
        WIND_D(3,IN_FLOOR) = FORCE2(I)/2D0 + FORCE_FRICTION2(I)
        ELSEIF (I.NE.1) THEN
        WIND_D(1,IN_FLOOR) = (FORCE1(I) + FORCE1(I-1))/2D0 + FORCE_FRICTION1(I)
        WIND_D(2,IN_FLOOR) = (FORCE2(I) + FORCE2(I-1))/2D0 + FORCE_FRICTION2(I)
        WIND_D(3,IN_FLOOR) = 0.0D0
        ENDIF
      ENDSELECT
      ENDDO
      
      END
      
C	==================================================================
      SUBROUTINE ROUGHNESS_FACTOR_EURO_1997 (IOPT_ROUGNESS,AKR,ZO,ZMIN)
      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT INTEGER*4 (i-n)
      
      SELECTCASE(IOPT_ROUGNESS)
      CASE (1)  ! I
      AKR = 0.17D0
      ZO  = 0.01D0
      ZMIN = 2.0D0
      CASE (2)  ! II
      AKR = 0.19D0
      ZO  = 0.05D0
      ZMIN = 4.0D0
      CASE (3)  ! III
      AKR = 0.22D0
      ZO  = 0.30D0
      ZMIN = 8.0D0    
      CASE (4)  ! IV
      AKR = 0.2D0
      ZO  = 1.0D0
      ZMIN = 16.0D0  
      ENDSELECT
      END